import fs from "node:fs";
import assert from "node:assert/strict";
const html=fs.readFileSync(new URL("../editor/content.html",import.meta.url),"utf8");
const js=fs.readFileSync(new URL("../editor/editor.js",import.meta.url),"utf8");
const ws=fs.readFileSync(new URL("../editor/workspace.js",import.meta.url),"utf8");
assert.match(html,/id="site-tree"/);
assert.match(html,/Editar portada/);
assert.match(html,/contenteditable="true"/);
assert.match(html,/data-command="bold"/);
assert.match(html,/data-command="italic"/);
assert.match(html,/data-command="smallcaps"/);
assert.match(html,/id="insert-image"/);
assert.match(js,/public\/images\//);
assert.match(js,/image\.loading = "lazy"/);
assert.match(js,/figcaption/);
assert.match(js,/buildHomepage/);
assert.match(js,/savePatch\("index\.html"/);
assert.match(ws,/value instanceof Blob/);
assert.ok(fs.existsSync(new URL("../public/images/.gitkeep",import.meta.url)));
console.log("Pruebas superadas: árbol, portada, editor enriquecido, imágenes y parches binarios.");
