import fs from "node:fs";
import assert from "node:assert/strict";
const panel=fs.readFileSync(new URL("../editor/index.html",import.meta.url),"utf8");
assert.match(panel,/href="hotspots\.html"/);
assert.match(panel,/href="content\.html"/);
assert.match(panel,/Editar hotspots/);
assert.match(panel,/Administrar contenido/);
const content=fs.readFileSync(new URL("../editor/content.html",import.meta.url),"utf8");
assert.match(content,/id="content-form"/);
assert.match(content,/href="hotspots\.html"/);
assert.match(content,/Guardar en la actualización/);
const hotspotHTML=fs.readFileSync(new URL("../editor/hotspots.html",import.meta.url),"utf8");
assert.match(hotspotHTML,/id="hotspot-stage"/);
const hotspots=JSON.parse(fs.readFileSync(new URL("../src/data/hotspots.json",import.meta.url),"utf8"));
assert.ok(Array.isArray(hotspots)&&hotspots.length>0);
console.log(`Pruebas superadas: panel, CMS y ${hotspots.length} hotspots conservados.`);
