"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
const SCALE={investigacion:{mode:"investigacion",hLabel:"capacidad institucional de esclarecer/reconstruir hechos con información verificable"},regulacion:{mode:"impacto_regulatorio",hLabel:"capacidad operativa del actor regulado para sostener su actividad"},narrativa:{mode:"supervivencia",hLabel:"capacidad conductual para sobrevivir, escapar, orientarse o recuperar agencia"},migracion:{mode:"migracion",hLabel:"capacidad institucional de sostener el procedimiento de recepción/repatriación relevante"},consumo:{mode:"adopcion",hLabel:"disposición conductual observable respecto del objeto"},generico:{mode:"generico",hLabel:"estado conductual observable respecto de la cuestión"}};
function concordance(raw,semantic){const S=ns.Spanish,ss=S.splitSentences(raw),freq={};ss.forEach(sent=>S.tokenize(sent).forEach(t=>{const l=t.lemma;if(!l||l.length<3||S.STOP.has(l)||/^\d+$/.test(l))return;freq[l]=(freq[l]||0)+1;}));const max=Math.max(1,...Object.values(freq));return Object.entries(freq).map(([term,count])=>({term,count,relevance:count/max,actors:[...new Set(semantic.frames.filter(f=>S.tokenize(f.evidence).some(t=>t.lemma===term)).map(f=>f.actor).filter(Boolean))]})).sort((a,b)=>b.relevance-a.relevance||b.count-a.count).slice(0,24);}
function mostFrequent(items){const m=new Map();items.filter(Boolean).forEach(x=>m.set(x,(m.get(x)||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"";}
function buildTracks(a){const d=a.events.domain.id,base=SCALE[d]||SCALE.generico,ops=a.events.operations;let candidates=ops,evaluated=mostFrequent(ops.map(o=>o.actionTarget));if(d==="regulacion")candidates=ops.filter(o=>/regulatory/.test(o.family));if(d==="narrativa")candidates=ops.filter(o=>/abandonment|capture|orientation|counteraction|return/.test(o.family));if(d==="investigacion")candidates=ops.filter(o=>/judicial|information|allegation/.test(o.family));if(d==="migracion")candidates=ops.filter(o=>/reception|mobility|migration/.test(o.family));return[{id:base.mode,label:`Track preliminar · ${d}`,evaluatedActor:evaluated,hLabel:base.hLabel,H0:null,anchors:{},candidateOperations:candidates,operations:candidates.filter(o=>o.coreEligible),status:{calculable:false,missing:["parámetros numéricos sólo si la evidencia los sustenta"],warnings:[],confidence:"preliminar"}}];}
function scenarioBase(a,tracks){const d=a.events.domain.id,base=SCALE[d]||SCALE.generico;return{issue:a.semiotic?.issueSuggestion||"transformación conductual respecto de la cuestión",note:`Dominio inferido: ${a.events.domain.label}. La semiótica y la mediación estratégica son el resultado principal; la cuantificación es selectiva.`,mode:tracks[0]?.id||base.mode,hLabel:tracks[0]?.hLabel||base.hLabel,H0:null,anchors:{}};}
async function analyze(raw){if(!raw.trim())throw new Error("No hay texto fuente.");const dictionary=await ns.Spanish.loadDictionary(),entities=ns.Entities.detect(raw),semantic=ns.Semantic.analyze(raw,entities),a={version:"v0.54-semantic-hierarchy",raw,entities,semantic};a.events=ns.Events.build(raw,semantic.frames,entities);a.concordance=concordance(raw,semantic);a.semiotic=ns.Synthesis.semiotic(a);a.tracks=buildTracks(a);a.scenario=scenarioBase(a,a.tracks);a.game=ns.Games.analyze(a);a.qualitative=ns.Synthesis.qualitative(a);a.dictionary=dictionary;return a;}
function actorValues(e,evaluated){return{id:e.name,role:e.role||e.type,hmode:e.name===evaluated?"sí":"no",S:null,E:null,H:null,evidence:{S:"Sin valor numérico sustentado.",E:"Sin valor numérico sustentado.",H:e.name===evaluated?"H cualitativamente interpretable; valor puntual no asignado.":"Actor no evaluado en esta escala."}};}
function actorsForTrack(a,track){return (a.entities||[]).filter(e=>e.operationalCandidate!==false).map(e=>actorValues(e,track.evaluatedActor));}
function operationsForTrack(a,track){return track.operations.map(o=>({...o,terminalG:null}));}
ns.Analysis={SCALE,concordance,analyze,buildTracks,actorsForTrack,operationsForTrack};
})(window);
