"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
const SCALE={
 investigacion:{issue:"capacidad de la investigación para esclarecer y reconstruir los hechos",mode:"investigacion",hLabel:"capacidad institucional de la investigación para esclarecer/reconstruir los hechos con información verificable",anchors:{"0.00":"sin capacidad de esclarecimiento o evidencia utilizable","0.25":"investigación abierta con información insuficiente","0.50":"capacidad parcial de reconstrucción y contraste","0.75":"esclarecimiento sustancial con evidencia verificable","1.00":"reconstrucción suficientemente estable y corroborada"}},
 regulacion:{issue:"impacto y respuesta frente a una restricción regulatoria",mode:"impacto_regulatorio",hLabel:"capacidad operativa del actor regulado para sostener su actividad",anchors:{"0.00":"exclusión total de la actividad","0.25":"actividad severamente restringida","0.50":"operación parcial","0.75":"operación viable con restricciones","1.00":"operación plena"}},
 narrativa:{issue:"transformación de supervivencia, libertad o agencia en la secuencia narrativa",mode:"supervivencia",hLabel:"capacidad conductual del actor evaluado para sobrevivir, escapar, orientarse o recuperar agencia",anchors:{"0.00":"indefensión o imposibilidad de actuar","0.25":"agencia muy limitada","0.50":"capacidad parcial de respuesta","0.75":"recuperación significativa de agencia","1.00":"agencia/resultado plenamente realizado"}},
 consumo:{issue:"adopción o cambio conductual del receptor",mode:"adopcion",hLabel:"disposición conductual observable respecto del objeto de intercambio",anchors:{"0.00":"rechazo","0.25":"exposición sin adopción","0.50":"consideración activa","0.75":"adopción probable","1.00":"adopción realizada"}},
 generico:{issue:"transformación conductual respecto de la cuestión",mode:"generico",hLabel:"estado conductual observable respecto de la cuestión",anchors:{"0.00":"estado mínimo","0.25":"estado bajo","0.50":"estado intermedio","0.75":"estado alto","1.00":"estado máximo"}}
};
function concordance(raw,semantic){const S=ns.Spanish,ss=S.splitSentences(raw),freq={},spread={};ss.forEach((sent,si)=>{const seen=new Set();S.tokenize(sent).forEach(t=>{const l=t.lemma;if(!l||l.length<3||S.STOP.has(l)||/^\d+$/.test(l))return;freq[l]=(freq[l]||0)+1;seen.add(l);});seen.forEach(l=>(spread[l]||(spread[l]=new Set())).add(si));});const max=Math.max(1,...Object.values(freq));const frameWeight={};semantic.frames.forEach(f=>S.tokenize(f.evidence).forEach(t=>{if(t.lemma&&!S.STOP.has(t.lemma))frameWeight[t.lemma]=(frameWeight[t.lemma]||0)+(f.type==="UNRESOLVED"?.1:f.relation_to_event==="constitutive"?1:.45);}));return Object.entries(freq).map(([term,count])=>{const sp=(spread[term]?.size||0)/Math.max(1,ss.length),rel=Math.min(1,(count/max)*.35+Math.min(1,sp*4)*.25+Math.min(1,(frameWeight[term]||0)/4)*.40),related=semantic.frames.filter(f=>S.tokenize(f.evidence).some(t=>t.lemma===term));return{term,count,spread:+sp.toFixed(3),relevance:+rel.toFixed(3),actors:[...new Set(related.map(f=>f.actor).filter(Boolean))].slice(0,5),predicates:[...new Set(related.map(f=>f.predicate).filter(Boolean))].slice(0,6)};}).sort((a,b)=>b.relevance-a.relevance||b.count-a.count).slice(0,24);}
function actorValues(entity,evaluated){return{id:entity.name,role:entity.role||entity.type,hmode:entity.name===evaluated?"sí":"no",S:null,E:null,H:null,numericStatus:"sin parametrizar",evidence:{S:"No inferido automáticamente. Declare S con evidencia pertinente al issue.",E:"No inferido automáticamente. Declare E con evidencia situada.",H:entity.name===evaluated?"No inferido automáticamente. Declare H inicial sobre la escala seleccionada.":"Actor no evaluado en esta escala H."}};}
function mostFrequent(items){const m=new Map();items.filter(Boolean).forEach(x=>m.set(x,(m.get(x)||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"";}
function trackDefs(analysis){const d=analysis.events.domain.id,base=SCALE[d]||SCALE.generico,ops=analysis.events.operations;
 if(d==="regulacion"){const restriction=ops.filter(o=>o.family==="regulatory_restriction"),challenge=ops.filter(o=>/regulatory_challenge|economic_argument|legitimacy_argument/.test(o.family)),affected=mostFrequent(restriction.map(o=>o.actionTarget))||mostFrequent(challenge.map(o=>o.source));const authority=mostFrequent(restriction.map(o=>o.source))||mostFrequent(challenge.map(o=>o.actionTarget));return[
  {id:"impacto_regulatorio",label:"Track A · impacto operativo",evaluatedActor:affected,hLabel:base.hLabel,anchors:base.anchors,candidates:restriction,coreCandidates:restriction.filter(o=>o.coreEligible),warnings:["La restricción material/normativa no entra automáticamente al núcleo comunicativo v0.40; requiere decisión teórica o modelado manual."]},
  {id:"impugnacion",label:"Track B · impugnación institucional",evaluatedActor:affected,hLabel:"capacidad/disposición observable del actor afectado para impugnar, presionar o modificar la norma",anchors:{"0.00":"nula capacidad de respuesta","0.25":"malestar sin acción efectiva","0.50":"impugnación inicial o presión parcial","0.75":"impugnación activa y sostenida","1.00":"modificación efectiva o presión institucional decisiva"},candidates:challenge,coreCandidates:challenge.filter(o=>o.coreEligible),warnings:authority?[]:["Destinatario institucional no resuelto con suficiente confianza."]}
 ];}
 if(d==="investigacion"){const legal=ops.filter(o=>/judicial_detention|information_request|communicative_operation/.test(o.family));return[{id:"investigacion",label:"Track · esclarecimiento investigativo",evaluatedActor:"investigación / autoridad",analyticActor:true,hLabel:base.hLabel,anchors:base.anchors,candidates:legal,coreCandidates:legal.filter(o=>o.coreEligible),warnings:["Las medidas materiales (detención, registro, traslado) no se convierten automáticamente en D del núcleo v0.40."]}];}
 if(d==="narrativa"){const threat=ops.filter(o=>/abandonment|capture/.test(o.family)),response=ops.filter(o=>/orientation|counteraction|return/.test(o.family)),evaluated=mostFrequent(threat.map(o=>o.actionTarget))||mostFrequent(response.map(o=>o.source));return[{id:"supervivencia",label:"Track narrativo · supervivencia/agencia",evaluatedActor:evaluated,hLabel:base.hLabel,anchors:base.anchors,candidates:[...threat,...response].sort((a,b)=>(a.episodeId||"").localeCompare(b.episodeId||"")),coreCandidates:[...threat,...response].filter(o=>o.coreEligible),warnings:["Las acciones materiales narrativas quedan fuera del núcleo comunicativo v0.40 salvo parametrización/justificación explícita."]}];}
 const candidates=ops.filter(o=>o.coreEligible),evaluated=mostFrequent(candidates.map(o=>o.actionTarget));return[{id:base.mode,label:"Track preliminar",evaluatedActor:evaluated,hLabel:base.hLabel,anchors:base.anchors,candidates,coreCandidates:candidates,warnings:[]}];}
function buildTracks(analysis){return trackDefs(analysis).map(d=>{const missing=[];if(!d.evaluatedActor)missing.push("actor evaluado");missing.push("H0");if(!d.coreCandidates.length)missing.push("operación comunicativa elegible v0.40");else missing.push("S/E/D/φ/G_e por parametrizar");return{id:d.id,label:d.label,evaluatedActor:d.evaluatedActor,hLabel:d.hLabel,H0:null,anchors:d.anchors,candidateOperations:d.candidates,operations:d.coreCandidates,status:{calculable:false,missing,warnings:d.warnings||[],confidence:d.coreCandidates.length?"preliminar":"baja"}};});}
function ensureActorsForTracks(analysis,tracks){const map=new Map(analysis.entities.filter(e=>e.operationalCandidate!==false).map(e=>[e.name,e]));for(const t of tracks){if(t.evaluatedActor&&!map.has(t.evaluatedActor))map.set(t.evaluatedActor,{name:t.evaluatedActor,type:"ANALYTIC_ACTOR",role:"actor analítico explícito",operationalCandidate:true});for(const o of t.operations){for(const id of [o.source,o.target])if(id&&!map.has(id))map.set(id,{name:id,type:"ANALYTIC_ACTOR",role:"actor derivado de frame",operationalCandidate:true});}}return [...map.values()];}
function scenarioBase(analysis,tracks){const d=analysis.events.domain.id,base=SCALE[d]||SCALE.generico;return{issue:base.issue,note:`Dominio inferido: ${analysis.events.domain.label}. v0.52.1 no asigna números desconocidos. El escenario queda preliminar hasta declarar S, E, H, D, φ y G_e con evidencia. Las acciones materiales/institucionales se conservan como observaciones, no como D comunicativa automática.`,mode:tracks[0]?.id||base.mode,hLabel:tracks[0]?.hLabel||base.hLabel,H0:null,anchors:tracks[0]?.anchors||base.anchors};}
async function analyze(raw){if(!raw.trim())throw new Error("No hay texto fuente.");const dictionary=await ns.Spanish.loadDictionary(),entities=ns.Entities.detect(raw),semantic=ns.Semantic.analyze(raw,entities),preliminary={version:"v0.52.1-integrity-recovery",raw,entities,semantic};preliminary.events=ns.Events.build(raw,semantic.frames,entities);preliminary.concordance=concordance(raw,semantic);preliminary.tracks=buildTracks(preliminary);preliminary.analysisEntities=ensureActorsForTracks(preliminary,preliminary.tracks);preliminary.scenario=scenarioBase(preliminary,preliminary.tracks);preliminary.game=ns.Games.analyze(preliminary);preliminary.dictionary=dictionary;return preliminary;}
function actorsForTrack(analysis,track){return ensureActorsForTracks(analysis,[track]).map(e=>actorValues(e,track.evaluatedActor));}
function operationsForTrack(analysis,track,scenario=null){return track.operations.map(o=>({...o,terminalG:null}));}
ns.Analysis={SCALE,concordance,analyze,buildTracks,actorsForTrack,operationsForTrack};
})(window);
