"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
const SCALE={
 investigacion:{issue:"capacidad de la investigación para esclarecer y reconstruir los hechos",mode:"investigacion",hLabel:"capacidad institucional de la investigación para esclarecer/reconstruir los hechos con información verificable",H0:.35,anchors:{"0.00":"sin capacidad de esclarecimiento o evidencia utilizable","0.25":"investigación abierta con información insuficiente","0.50":"capacidad parcial de reconstrucción y contraste","0.75":"esclarecimiento sustancial con evidencia verificable","1.00":"reconstrucción suficientemente estable y corroborada"}},
 regulacion:{issue:"impacto y respuesta frente a una restricción regulatoria",mode:"impacto_regulatorio",hLabel:"capacidad operativa del actor regulado para sostener su actividad",H0:.70,anchors:{"0.00":"exclusión total de la actividad","0.25":"actividad severamente restringida","0.50":"operación parcial","0.75":"operación viable con restricciones","1.00":"operación plena"}},
 narrativa:{issue:"supervivencia, escape y recuperación de agencia de los actores vulnerables",mode:"supervivencia",hLabel:"capacidad conductual de sobrevivir, escapar, orientarse o recuperar agencia",H0:.25,anchors:{"0.00":"indefensión, captura o imposibilidad de retorno","0.25":"supervivencia precaria sin control del entorno","0.50":"capacidad parcial de orientación, resistencia o escape","0.75":"escape probable y recuperación significativa de agencia","1.00":"supervivencia lograda, retorno o agencia restaurada"}},
 consumo:{issue:"adopción o cambio conductual del receptor",mode:"adopcion",hLabel:"disposición conductual observable respecto del objeto de intercambio",H0:.30,anchors:{"0.00":"rechazo","0.25":"exposición sin adopción","0.50":"consideración activa","0.75":"adopción probable","1.00":"adopción realizada"}},
 generico:{issue:"transformación conductual respecto del issue",mode:"generico",hLabel:"estado conductual observable respecto del issue",H0:.50,anchors:{"0.00":"estado mínimo","0.25":"estado bajo","0.50":"estado intermedio","0.75":"estado alto","1.00":"estado máximo"}}
};
function concordance(raw,semantic,entities){const S=ns.Spanish,ss=S.splitSentences(raw),freq={},spread={};ss.forEach((sent,si)=>{const seen=new Set();S.tokenize(sent).forEach(t=>{const l=t.lemma;if(!l||l.length<3||S.STOP.has(l)||/^\d+$/.test(l))return;freq[l]=(freq[l]||0)+1;seen.add(l);});seen.forEach(l=>(spread[l]||(spread[l]=new Set())).add(si));});const max=Math.max(1,...Object.values(freq));const frameWeight={};semantic.frames.forEach(f=>S.tokenize(f.evidence).forEach(t=>{if(t.lemma&&!S.STOP.has(t.lemma))frameWeight[t.lemma]=(frameWeight[t.lemma]||0)+(f.relation_to_event==="constitutive"?1.2:.5);}));return Object.entries(freq).map(([term,count])=>{const sp=(spread[term]?.size||0)/Math.max(1,ss.length),rel=Math.min(1,(count/max)*.35+Math.min(1,sp*4)*.25+Math.min(1,(frameWeight[term]||0)/4)*.40);const related=semantic.frames.filter(f=>S.tokenize(f.evidence).some(t=>t.lemma===term));return{term,count,spread:+sp.toFixed(3),relevance:+rel.toFixed(3),actors:[...new Set(related.map(f=>f.actor).filter(Boolean))].slice(0,5),predicates:[...new Set(related.map(f=>f.predicate).filter(Boolean))].slice(0,6)};}).sort((a,b)=>b.relevance-a.relevance||b.count-a.count).slice(0,24);}
function actorValues(entity,evaluated,H0){let S=.55,E=.55;if(entity.type==="INSTITUTION"||entity.type==="GOVERNMENT"||entity.type==="COURT_ROLE"){S=.68;E=.78;}if(entity.type==="PERSON"){S=.60;E=.55;}if(entity.type==="COLLECTIVE"){S=.58;E=.60;}if(/bruja|madrastra|padre|Hänsel|Gretel/.test(entity.name)){S=.78;E=.72;}if(entity.name==="Hänsel y Gretel"){S=.75;E=.68;}return{id:entity.name,role:entity.role||entity.type,hmode:entity.name===evaluated?"sí":"no",S,E,H:entity.name===evaluated?H0:.50,numericStatus:"heurístico/confirmable",evidence:{S:`Tipo/rol detectado: ${entity.type} · ${entity.role||"sin rol"}.`,E:`Posición inferida desde menciones y función textual; requiere confirmación.`,H:entity.name===evaluated?"H inicial sugerida por perfil/estado textual; requiere confirmación.":"Actor no evaluado en esta escala H."}};}
function trackDefs(analysis){const d=analysis.events.domain.id,base=SCALE[d]||SCALE.generico;if(d==="regulacion")return[
 {id:"impacto_regulatorio",label:"Track A · impacto operativo",evaluatedActor:"Comunidad de Pequeños Anfitriones",hLabel:base.hLabel,H0:.70,anchors:base.anchors,operationFilter:o=>o.family==="regulatory_restriction"},
 {id:"impugnacion",label:"Track B · impugnación institucional",evaluatedActor:"Comunidad de Pequeños Anfitriones",hLabel:"capacidad/disposición del actor afectado para impugnar, presionar o modificar la norma",H0:.40,anchors:{"0.00":"nula capacidad de respuesta","0.25":"malestar sin acción efectiva","0.50":"impugnación inicial o presión parcial","0.75":"impugnación activa y sostenida","1.00":"modificación efectiva o presión institucional decisiva"},operationFilter:o=>/challenge|argument/.test(o.family)}];
 if(d==="investigacion"){const fgr=analysis.entities.find(e=>/Fiscalía General de la República/.test(e.name))?.name||analysis.entities.find(e=>/Fiscal/i.test(e.name))?.name||"investigación / autoridad";return[{id:"investigacion",label:"Track · esclarecimiento investigativo",evaluatedActor:fgr,hLabel:base.hLabel,H0:base.H0,anchors:base.anchors,operationFilter:o=>o.family==="judicial_detention"&&o.calculable}];}
 if(d==="narrativa")return[{id:"supervivencia",label:"Track narrativo · supervivencia/agencia",evaluatedActor:"Hänsel y Gretel",hLabel:base.hLabel,H0:base.H0,anchors:base.anchors,operationFilter:o=>o.calculable}];
 const ev=analysis.entities.find(e=>e.operationalCandidate!==false)?.name||analysis.entities[0]?.name||"actor evaluado";return[{id:base.mode,label:"Track principal",evaluatedActor:ev,hLabel:base.hLabel,H0:base.H0,anchors:base.anchors,operationFilter:o=>o.calculable}];}
function buildTracks(analysis){const defs=trackDefs(analysis);return defs.map(d=>{const ops=analysis.events.operations.filter(d.operationFilter).map(o=>({...o,target:d.evaluatedActor,stateTarget:d.evaluatedActor}));const missing=[];if(!d.evaluatedActor)missing.push("actor evaluado");if(!ops.length)missing.push("operaciones causales realizadas");return{id:d.id,label:d.label,evaluatedActor:d.evaluatedActor,hLabel:d.hLabel,H0:d.H0,anchors:d.anchors,operations:ops,status:{calculable:!missing.length,missing,confidence:ops.length?"media":"baja"}};});}
function ensureActorsForTracks(analysis,tracks){const map=new Map(analysis.entities.filter(e=>e.operationalCandidate!==false).map(e=>[e.name,e]));for(const t of tracks){if(!map.has(t.evaluatedActor))map.set(t.evaluatedActor,{name:t.evaluatedActor,type:"ANALYTIC_ACTOR",role:"actor evaluado",operationalCandidate:true});for(const o of t.operations){if(!map.has(o.source))map.set(o.source,{name:o.source,type:"ANALYTIC_ACTOR",role:"fuente operativa",operationalCandidate:true});}}
 return [...map.values()];}
function scenarioBase(analysis,tracks){const d=analysis.events.domain.id,base=SCALE[d]||SCALE.generico;let note=`Dominio inferido: ${analysis.events.domain.label}. La salida numérica es una propuesta confirmable; frames hipotéticos, atribuidos o meramente evaluativos no se convierten automáticamente en operaciones causales.`;if(d==="investigacion")note+=" La detención es un hecho institucional; su eventual aporte al esclarecimiento permanece como proyección hasta observar información nueva.";return{issue:base.issue,note,mode:tracks[0]?.id||base.mode,hLabel:tracks[0]?.hLabel||base.hLabel,H0:tracks[0]?.H0??base.H0,anchors:tracks[0]?.anchors||base.anchors};}
async function analyze(raw){if(!raw.trim())throw new Error("No hay texto fuente.");const dictionary=await ns.Spanish.loadDictionary();const entities=ns.Entities.detect(raw);const semantic=ns.Semantic.analyze(raw,entities);const preliminary={version:"v0.52-language-frames-game-ontology",raw,entities,semantic};preliminary.events=ns.Events.build(raw,semantic.frames,entities);preliminary.concordance=concordance(raw,semantic,entities);preliminary.tracks=buildTracks(preliminary);preliminary.analysisEntities=ensureActorsForTracks(preliminary,preliminary.tracks);preliminary.scenario=scenarioBase(preliminary,preliminary.tracks);preliminary.game=ns.Games.analyze(preliminary);preliminary.dictionary=dictionary;return preliminary;}
function actorsForTrack(analysis,track){return ensureActorsForTracks(analysis,[track]).map(e=>actorValues(e,track.evaluatedActor,track.H0));}
function operationsForTrack(analysis,track,scenario=null){const terminalG=scenario?.terminalG?.[track.id];return track.operations.map(o=>({...o,terminalG:Number.isFinite(terminalG)?terminalG:null}));}
ns.Analysis={SCALE,concordance,analyze,buildTracks,actorsForTrack,operationsForTrack};
})(window);
