"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],num=v=>{const x=Number(v);return Number.isFinite(x)?x:NaN;};let lastAnalysis=null,lastScenario=null;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function fmt(v){return Number.isFinite(v)?v.toFixed(3):"—";}
function renderAnalysis(a){const top=a.concordance.slice(0,10),frames=a.semantic.frames,game=a.game;$("#textOut").innerHTML=`<b>Análisis estructurado</b>
<div class="metric"><span>Dominio</span><b>${esc(a.events.domain.label)} · ${a.events.domain.score.toFixed(2)}</b></div>
<div class="metric"><span>Diccionario es_MX</span><b>${esc(a.dictionary.status)} · ${a.dictionary.size||0} entradas · ${a.dictionary.affixRules||0} reglas</b></div>
<div class="metric"><span>Entidades</span><b>${a.entities.length}</b></div>
<div class="metric"><span>Frames</span><b>${frames.length} · SER ${a.semantic.stats.ser} · ESTAR ${a.semantic.stats.estar} · DECIR ${a.semantic.stats.decir} · HACER ${a.semantic.stats.hacer}</b></div>
<div class="metric"><span>Episodios</span><b>${a.events.episodes.length} · operaciones causales ${a.events.calculableOperations.length}</b></div>
<h3>Entidades</h3>${a.entities.map(e=>`<div class="candidate"><b>${esc(e.name)}</b><span class="badge">${esc(e.type)}</span><div class="snippet">${esc(e.role||"—")} · menciones=${e.mentions.length} · ${esc(e.confidence)}</div></div>`).join("")||"<div class='snippet'>Sin entidades suficientes.</div>"}
<h3>Concordancia semántica</h3><div class="candidate">${top.map(t=>`<div class="snippet"><b>${esc(t.term)}</b> f=${t.count} · rel=${t.relevance.toFixed(3)} · actores=${esc(t.actors.join(", ")||"—")} · predicados=${esc(t.predicates.join(", ")||"—")}</div>`).join("")}</div>
<h3>Frames</h3>${frames.slice(0,24).map(f=>`<div class="candidate"><b>${esc(f.id)} · ${esc(f.type)} · ${esc(f.sense||f.predicate||"—")}</b><span class="badge">${esc(f.realization)}</span><span class="badge">${esc(f.epistemic_status)}</span><div class="snippet">actor=${esc(f.actor||"—")} · paciente=${esc(f.patient||"—")} · destinatario=${esc(f.recipient||"—")} · objeto=${esc(f.object||"—")}</div><div class="snippet">función=${esc(f.relation_to_event)} · lógica=${esc(f.logic.join(",")||"—")}</div><div class="snippet">${esc(f.evidence)}</div></div>`).join("")}
<h3>Episodios / coreferencia</h3>${a.events.episodes.map(e=>`<div class="candidate"><b>${esc(e.id)} · ${esc(e.family)}</b><span class="badge">evidencias ${e.evidenceCount}</span><span class="badge">${esc(e.confidence)}</span><div class="snippet">realización=${esc(e.realizationStatus.join(", "))} · estatus=${esc(e.epistemicStatus.join(", "))}</div></div>`).join("")}
<h3>Ontología de juegos</h3><div class="candidate"><b>${game.catalogSize} plantillas canónicas disponibles</b><div class="snippet">Juego determinado: ${game.determined?esc(game.determined.label)+" · "+game.determined.score.toFixed(2):"no; se muestran candidatos"}</div>${game.candidates.slice(0,6).map(g=>`<div class="snippet">${esc(g.label)} · ${g.score.toFixed(2)} · faltan: ${esc(g.missing.join(", ")||"ninguno")}</div>`).join("")}</div>
<h3>Subjuegos / estructura estratégica</h3>${game.subgames.map(s=>`<div class="candidate"><b>${esc(s.id)} · ${esc(s.label)}</b><div class="snippet">${esc(s.sequence.join(" → "))} · ${esc(s.status)}</div></div>`).join("")||"<div class='snippet'>Sin subjuegos suficientemente estructurados.</div>"}
<h3>Tracks</h3>${a.tracks.map(t=>`<div class="candidate"><b>${esc(t.label)}</b><span class="badge">${t.status.calculable?"calculable":"preliminar"}</span><div class="snippet">H=${esc(t.hLabel)} · actor=${esc(t.evaluatedActor)} · H0=${t.H0.toFixed(2)} · operaciones=${t.operations.length}</div></div>`).join("")}`;}
function populateScenarios(a){const s=$("#strategicScenario");s.innerHTML=`<option value="">sin seleccionar</option>`+a.game.scenarios.map((x,i)=>`<option value="${i}">${esc(x.label)} · ${esc(x.confidence)}</option>`).join("");}
async function analyzeText(){const raw=$("#corpus").value.trim();lastAnalysis=await ns.Analysis.analyze(raw);populateScenarios(lastAnalysis);renderAnalysis(lastAnalysis);return lastAnalysis;}
function setScale(track){$("#hLabel").value=track.hLabel;for(const k of ["0.00","0.25","0.50","0.75","1.00"]){const id={"0.00":"h0","0.25":"h25","0.50":"h50","0.75":"h75","1.00":"h100"}[k];$("#"+id).value=track.anchors[k]||"";}}
function actorRow(a){return `<tr><td><input value="${esc(a.id)}"></td><td><input value="${esc(a.role)}"></td><td><select class="hmode"><option value="${a.hmode}">${a.hmode}</option><option value="${a.hmode==="sí"?"no":"sí"}">${a.hmode==="sí"?"no":"sí"}</option></select></td><td><input type="number" step=".01" min="0" max="1" value="${a.S.toFixed(2)}"></td><td><input type="number" step=".01" min="0" max="1" value="${a.E.toFixed(2)}"></td><td><input type="number" step=".01" min="0" max="1" value="${a.H.toFixed(2)}"></td><td class="derived">${(a.S*a.E).toFixed(3)}</td><td><textarea class="evS">${esc(a.evidence.S)}</textarea><textarea class="evE">${esc(a.evidence.E)}</textarea><textarea class="evH">${esc(a.evidence.H)}</textarea></td><td><button class="smallbtn danger removeActor">×</button></td></tr>`;}
function opRow(o){return `<tr data-action-target="${esc(o.actionTarget||o.target)}" data-state-target="${esc(o.stateTarget||o.target)}" data-episode="${esc(o.episodeId||"")}" data-terminal-g="${Number.isFinite(o.terminalG)?o.terminalG:""}"><td><select class="source"></select></td><td><select class="target"></select></td><td><input class="optype" value="${esc(o.type)}"></td><td><input type="number" step=".01" min="0" max="1" value="${o.D.toFixed(2)}"></td><td><input type="number" step=".01" min="0" max="1" value="${o.phi.toFixed(2)}"></td><td><input type="number" step=".01" min="0" max="1" value="${o.G.toFixed(2)}"></td><td><textarea class="evD">${esc(o.evidence.D||"")}</textarea><textarea class="evPhi">${esc(o.evidence.phi||"")}</textarea><textarea class="evG">${esc(o.evidence.G||"")}</textarea></td><td><button class="smallbtn danger removeOp">×</button></td></tr>`;}
function actorRows(){return $$("#actors tbody tr");}function opRows(){return $$("#ops tbody tr");}function actorIds(){return actorRows().map(r=>r.querySelector("td input").value.trim()).filter(Boolean);}
function syncSelects(){const ids=actorIds();opRows().forEach(r=>{const s=r.querySelector(".source"),t=r.querySelector(".target"),ps=s.dataset.want||s.value,pt=t.dataset.want||t.value,opts=ids.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join("");s.innerHTML=opts;t.innerHTML=opts;s.value=ids.includes(ps)?ps:(ids[0]||"");t.value=ids.includes(pt)?pt:(ids[1]||ids[0]||"");});}
function selectedScenario(){if(!lastAnalysis)return null;const v=$("#strategicScenario").value;return v===""?null:lastAnalysis.game.scenarios[Number(v)]||null;}
function loadTextEvidence(){if(!lastAnalysis)throw new Error("Primero analice el texto.");const track=lastAnalysis.tracks.find(t=>t.status.calculable)||lastAnalysis.tracks[0];if(!track)throw new Error("No se generó ningún track.");const scenario=selectedScenario();$("#issue").value=lastAnalysis.scenario.issue;$("#scenarioNote").value=lastAnalysis.scenario.note+(scenario?` Escenario estratégico seleccionado: ${scenario.label}.`:"");$("#issueMode").value=track.id;setScale(track);const actors=ns.Analysis.actorsForTrack(lastAnalysis,track),ops=ns.Analysis.operationsForTrack(lastAnalysis,track,scenario);$("#actors tbody").innerHTML=actors.map(actorRow).join("");$("#ops tbody").innerHTML=ops.map(opRow).join("");syncSelects();opRows().forEach((r,i)=>{r.querySelector(".source").dataset.want=ops[i].source;r.querySelector(".target").dataset.want=ops[i].target;});syncSelects();refreshDerived();}
function readActors(){return actorRows().map(r=>{const ins=r.querySelectorAll("input");return{id:ins[0].value.trim(),role:ins[1].value.trim(),hmode:r.querySelector(".hmode").value,S:num(ins[2].value),E:num(ins[3].value),H:num(ins[4].value),evidence:{S:r.querySelector(".evS").value.trim(),E:r.querySelector(".evE").value.trim(),H:r.querySelector(".evH").value.trim()}};});}
function readOperations(){const issue=$("#issue").value.trim();return opRows().map(r=>{const inputs=r.querySelectorAll('input[type="number"]'),tg=Number(r.dataset.terminalG);return{issue,source:r.querySelector(".source").value,target:r.querySelector(".target").value,actionTarget:r.dataset.actionTarget||r.querySelector(".target").value,stateTarget:r.dataset.stateTarget||r.querySelector(".target").value,episodeId:r.dataset.episode||"",terminalG:Number.isFinite(tg)?tg:null,type:r.querySelector(".optype").value.trim(),D:num(inputs[0].value),phi:num(inputs[1].value),G:num(inputs[2].value),evidence:{D:r.querySelector(".evD").value.trim(),phi:r.querySelector(".evPhi").value.trim(),G:r.querySelector(".evG").value.trim()}};});}
function hScale(){return{label:$("#hLabel").value.trim(),anchors:{"0.00":$("#h0").value.trim(),"0.25":$("#h25").value.trim(),"0.50":$("#h50").value.trim(),"0.75":$("#h75").value.trim(),"1.00":$("#h100").value.trim()}};}
function buildScenario(){const issue=$("#issue").value.trim(),actors=readActors(),operations=readOperations();if(!issue)throw new Error("Debe declararse una cuestión específica.");if(actors.length<2)throw new Error("Se requieren al menos dos actores operativos para calcular.");if(!operations.length)throw new Error("No hay operaciones causales calculables. Revise frames/realización o añada una operación manual.");return{version:"v0.52-language-frames-game-ontology",issue,mode:$("#issueMode").value,note:$("#scenarioNote").value.trim(),hScale:hScale(),analysis:lastAnalysis,strategicScenario:selectedScenario(),input:{actors,operations},result:ns.Core.runSequence(actors,operations)};}
function nearest(v,scale){const ks=[0,.25,.5,.75,1],k=ks.reduce((b,x)=>Math.abs(x-v)<Math.abs(b-v)?x:b,ks[0]);return`${v.toFixed(3)} · cercano a ${k.toFixed(2)}: ${scale.anchors[k.toFixed(2)]||""}`;}
function renderScenario(s){lastScenario=s;$("#status").className="card ok";$("#status").innerHTML=`<b>${esc(s.issue)}</b><div class="metric"><span>Operaciones</span><b>${s.result.history.length}</b></div><div class="metric"><span>Juego principal/candidato</span><b>${esc(s.analysis?.game?.determined?.label||s.analysis?.game?.candidates?.[0]?.label||"indeterminado")}</b></div>`;$("#results").innerHTML=s.result.history.map((r,i)=>`<div class="card"><b>${i+1}. ${esc(r.source)} → ${esc(r.actionTarget||r.target)}</b><span class="badge">H afectado: ${esc(r.target)}</span><div class="metric"><span>R · D · φ · X</span><b>${fmt(r.R)} · ${fmt(r.D)} · ${fmt(r.phi)} · ${fmt(r.X)}</b></div><div class="metric"><span>H antes → G_e → H después</span><b>${fmt(r.Hbefore)} → ${fmt(r.G)} → ${fmt(r.Hafter)}</b></div><div class="metric"><span>ΔH</span><b>${r.deltaH>=0?"+":""}${fmt(r.deltaH)}</b></div>${Number.isFinite(r.terminalG)?`<div class="metric"><span>Gτ terminal</span><b>${fmt(r.terminalG)} (no sustituye G_e)</b></div>`:""}</div>`).join("")+`<div class="card"><b>Estado final</b>${s.result.actors.map(a=>`<div class="metric"><span>${esc(a.id)}</span><b>${a.hmode==="sí"?esc(nearest(a.H,s.hScale)):"H no evaluado"}</b></div>`).join("")}</div>`;$("#report").textContent=buildReport(s);}
function buildReport(s){const a=s.analysis,lines=["REPORTE DE ESCENARIO — LIMES v0.52","======================================","","Issue: "+s.issue,"Modo: "+s.mode];if(s.note)lines.push("Contexto: "+s.note);lines.push("","Escala H: "+s.hScale.label);Object.entries(s.hScale.anchors).forEach(([k,v])=>lines.push(`- ${k}: ${v}`));if(a){lines.push("","0A. RECURSOS LINGÜÍSTICOS",`Diccionario es_MX: ${a.dictionary.status} · ${a.dictionary.size||0} entradas · ${a.dictionary.affixRules||0} reglas Hunspell procesables`,`Dominio: ${a.events.domain.label} · ${a.events.domain.score.toFixed(2)}`);lines.push("","0B. ENTIDADES");a.entities.forEach(e=>lines.push(`- ${e.name} | ${e.type} | ${e.role||"—"} | menciones=${e.mentions.length} | ${e.confidence}`));lines.push("","0C. FRAMES SEMÁNTICOS");a.semantic.frames.slice(0,80).forEach(f=>lines.push(`- ${f.id} | ${f.type}/${f.sense||f.predicate||"—"} | actor=${f.actor||"—"} | paciente=${f.patient||"—"} | objeto=${f.object||"—"} | realización=${f.realization} | epistemic=${f.epistemic_status} | función=${f.relation_to_event} | lógica=${f.logic.join(",")||"—"}\n  Evidencia: ${f.evidence}`));lines.push("","0D. EPISODIOS / COREFERENCIA");a.events.episodes.forEach(e=>{lines.push(`- ${e.id} | ${e.family} | evidencias=${e.evidenceCount} | ${e.confidence} | realización=${e.realizationStatus.join(",")}`);e.evidence.slice(0,3).forEach(x=>lines.push(`  Evidencia: ${x}`));});lines.push("","0E. JUEGOS");lines.push(`Catálogo: ${a.game.catalogSize} plantillas canónicas.`);a.game.candidates.slice(0,8).forEach((g,i)=>lines.push(`${i+1}. ${g.label} | score=${g.score.toFixed(2)} | matched=${g.matched.join(",")||"—"} | missing=${g.missing.join(",")||"—"}`));lines.push(`Determinación: ${a.game.determined?a.game.determined.label:"indeterminada; conservar candidatos"}`);a.game.players.forEach(p=>lines.push(`Jugador/rol potencial: ${p.id} | ${p.role} | estrategias observadas/posibles=${p.observedStrategies.join(", ")} | preferencias=${p.preferenceStatus}`));a.game.subgames.forEach(g=>lines.push(`Subjuego ${g.id}: ${g.label} | ${g.sequence.join(" → ")} | ${g.status}`));lines.push("","0F. TRACKS");a.tracks.forEach(t=>lines.push(`- ${t.label} | H=${t.hLabel} | actor=${t.evaluatedActor} | H0=${t.H0.toFixed(2)} | operaciones=${t.operations.length} | ${t.status.calculable?"calculable":"preliminar"}`));}
lines.push("","1. ACTORES");s.input.actors.forEach(x=>lines.push(`- ${x.id} (${x.role}) | S=${x.S.toFixed(3)} E=${x.E.toFixed(3)} H=${x.H.toFixed(3)} R=${(x.S*x.E).toFixed(3)} | ${x.numericStatus||""}`));lines.push("","2. OPERACIONES Y DESPLAZAMIENTOS");s.result.history.forEach((r,i)=>{lines.push(`${i+1}. ${r.source} → ${r.actionTarget||r.target} | H afectado=${r.target} | ${r.type} | episodio=${r.episodeId||"—"}`);lines.push(`   R=${fmt(r.R)} · D=${fmt(r.D)} · φ=${fmt(r.phi)} · X=${fmt(r.X)}`);lines.push(`   H antes=${fmt(r.Hbefore)} · G_e=${fmt(r.G)} · ΔH=${r.deltaH>=0?"+":""}${fmt(r.deltaH)} · H después=${fmt(r.Hafter)}`);if(Number.isFinite(r.terminalG))lines.push(`   Gτ=${fmt(r.terminalG)} · marco terminal, no entra directamente en esta operación.`);});lines.push("","3. ESTADO FINAL");s.input.actors.forEach(x=>{const f=s.result.actors.find(y=>y.id===x.id)||x;lines.push(`- ${x.id}: ${x.hmode==="sí"?nearest(f.H,s.hScale):"H no evaluado"}`);});lines.push("","Nota metodológica: el diccionario mejora cobertura léxica/morfológica; los frames determinan sentido y estatus. Una mención repetida acumula evidencia, no impactos. Hechos atribuidos, hipótesis, expectativas y planes no se convierten automáticamente en operaciones causales. El catálogo de juegos conserva candidatos cuando faltan preferencias, información o estructura suficiente.");return lines.join("\n");}
function download(name,content,type){const b=new Blob([content],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href);}
function refreshDerived(){const A=readActors();actorRows().forEach((r,i)=>{try{r.querySelector(".derived").textContent=ns.Core.symbolicResources(A[i]).toFixed(3);}catch{r.querySelector(".derived").textContent="—";}});syncSelects();}
function addActor(){$("#actors tbody").insertAdjacentHTML("beforeend",actorRow({id:"",role:"",hmode:"no",S:.5,E:.5,H:.5,evidence:{S:"",E:"",H:""}}));refreshDerived();}
function addOp(){const o={source:"",target:"",actionTarget:"",stateTarget:"",type:"",D:.5,phi:.5,G:.5,evidence:{D:"",phi:"",G:""}};$("#ops tbody").insertAdjacentHTML("beforeend",opRow(o));syncSelects();}
$("#analyzeText").onclick=async()=>{try{await analyzeText();}catch(e){$("#textOut").className="card warn";$("#textOut").innerHTML=`<b>Error</b><p>${esc(e.message)}</p>`;}};$("#loadTextEvidence").onclick=()=>{try{loadTextEvidence();}catch(e){$("#status").className="card warn";$("#status").innerHTML=`<b>No generado</b><p>${esc(e.message)}</p>`;}};$("#addActor").onclick=addActor;$("#addOp").onclick=addOp;$("#actors").addEventListener("input",refreshDerived);$("#actors").addEventListener("click",e=>{if(e.target.classList.contains("removeActor")){e.target.closest("tr").remove();refreshDerived();}});$("#ops").addEventListener("click",e=>{if(e.target.classList.contains("removeOp")){e.target.closest("tr").remove();refreshDerived();}});$("#run").onclick=()=>{try{renderScenario(buildScenario());}catch(e){$("#status").className="card warn";$("#status").innerHTML=`<b>No ejecutado</b><p>${esc(e.message)}</p>`;}};$("#exportTxt").onclick=()=>{if(!lastScenario){try{renderScenario(buildScenario());}catch(e){alert(e.message);return;}}download("Limes_v052_reporte.txt",buildReport(lastScenario),"text/plain;charset=utf-8");};$("#exportJson").onclick=()=>{if(!lastScenario){try{renderScenario(buildScenario());}catch(e){alert(e.message);return;}}download("Limes_v052_escenario.json",JSON.stringify(lastScenario,null,2),"application/json;charset=utf-8");};
$("#jscheck").className="card ok";$("#jscheck").innerHTML=`<b>Módulos JS activos</b><p>Core · español · entidades · frames · eventos · ontología de juegos (${ns.GameOntology.count}) · motor estratégico · análisis · interfaz.</p>`;
ns.App={analyzeText,loadTextEvidence,buildScenario,buildReport,get lastAnalysis(){return lastAnalysis;}};
})(window);
