"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let lastAnalysis=null,lastQuantification=null;
const num=v=>{const s=String(v??"").trim();if(!s)return NaN;const x=Number(s);return Number.isFinite(x)?x:NaN;};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fmt=v=>Number.isFinite(v)?v.toFixed(3):"—";
const inputVal=v=>Number.isFinite(v)?v.toFixed(2):"";
const clip=(s,n=220)=>{s=String(s||"").replace(/\s+/g," ").trim();return s.length>n?s.slice(0,n-1)+"…":s;};
function list(items,empty="No identificado con suficiente evidencia."){return items?.length?`<ul>${items.map(x=>`<li>${x}</li>`).join("")}</ul>`:`<p class="note">${esc(empty)}</p>`;}
function stateLine(a,key,label){const ev=a[key]||[];return ev.length?`<div class="state-read"><b>${label}</b><span>${esc(clip(ev[0],180))}${ev.length>1?` <small>+${ev.length-1} evidencia${ev.length-1===1?"":"s"}</small>`:""}</span></div>`:"";}
function renderQualitative(a){
 const s=a.semiotic,q=a.qualitative;
 $("#qualitativeResult").innerHTML=`<h2>Análisis cualitativo</h2>
 <div class="card ok"><b>Lectura sintética</b><p>${esc(q.analysisSummary||"La estructura cualitativa es parcialmente interpretable.")}</p><div class="metric"><span>Dominio de lectura</span><b>${esc(a.events.domain.label)} · confianza ${a.events.domain.score.toFixed(2)}</b></div><div class="metric"><span>Issue propuesta</span><b>${esc(a.scenario.issue)}</b></div></div>
 <div class="card"><b>Actores y configuración</b>${s.actors.slice(0,8).map(x=>`<div class="actor-summary"><div><strong>${esc(x.id)}</strong><span class="badge">${esc(x.role||x.type)}</span></div>${stateLine(x,"ser","Ser")}${stateLine(x,"estar","Estar")}${stateLine(x,"decir","Decir")}${stateLine(x,"hacer","Hacer")}${!x.ser.length&&!x.estar.length&&!x.decir.length&&!x.hacer.length?`<p class="note">Actor identificado; configuración funcional no suficientemente explicitada.</p>`:""}</div>`).join("")}</div>
 <div class="grid2">
  <div class="card"><b>Objetos de valor / objetos en disputa</b>${s.valueObjects.length?s.valueObjects.map(o=>`<div class="candidate"><strong>${esc(o.object)}</strong><span class="badge">${esc(o.kind||"objeto")}</span><div class="snippet">actores vinculados: ${esc(o.actors.join(", ")||"—")} · evidencias=${o.count}</div></div>`).join(""):`<p class="note">No se reconstruyó un objeto de valor suficientemente estable.</p>`}</div>
  <div class="card"><b>Oposiciones</b>${s.oppositions.length?s.oppositions.map(o=>`<div class="candidate"><strong>${esc(o.left)} ↔ ${esc(o.right)}</strong><div class="snippet">${esc(o.status)}</div></div>`).join(""):`<p class="note">No se identificó una oposición estructural con suficiente apoyo.</p>`}</div>
 </div>
 <div class="card"><b>Programas y contra-programas</b>${s.programs.length?s.programs.slice(0,10).map(p=>`<div class="candidate"><strong>${esc(p.label||p.id)} · ${esc(p.actor)}</strong><span class="badge">${esc(p.orientation)}</span><div class="snippet">objetivo=${esc(p.goal||p.object||"—")} · acciones=${esc(p.actions.join(", ")||"—")}</div></div>`).join(""):`<p class="note">No se reconstruyeron programas suficientemente estables.</p>`}${s.counterPrograms.length?`<div class="subhead">Relaciones contrapuestas</div>${s.counterPrograms.map(c=>`<div class="snippet">${esc(c.a)} ↔ ${esc(c.b)} · ${esc(c.actors.join(" / "))} · objeto=${esc(c.object||"—")}</div>`).join("")}`:""}</div>
 <div class="card"><b>Fronteras interpretadas</b>${s.frontiers.length?s.frontiers.map(f=>`<div class="candidate"><strong>${esc(f.source)} → ${esc(f.target)}</strong><span class="badge">${esc(f.kind)}</span><div class="snippet">${esc(f.condition)}</div></div>`).join(""):`<p class="note">No se identificaron fronteras source→target suficientemente explícitas.</p>`}</div>`;
}
function renderStrategic(a){const st=a.qualitative.strategic;$("#strategicResult").innerHTML=`<h2>Mediación estratégica y extrapolación</h2><div class="card"><b>${esc(st.label)}</b><span class="badge">${esc(st.status)}</span><p class="note">La teoría de juegos organiza relaciones estratégicas ya interpretadas; no mide variables Limes.</p>${st.basis.length?`<div class="subhead">Base interpretable</div>${list(st.basis.map(esc))}`:""}${st.scenarios.length?`<div class="subhead">Escenarios cualitativos extrapolables</div>${st.scenarios.map((x,i)=>`<div class="scenario"><strong>${i+1}. ${esc(x.label)}</strong><p>${esc(x.projection)}</p><div class="snippet">Base: ${esc(x.basis)} · Límite: ${esc(x.limit)}</div></div>`).join("")}`:`<p class="note">La estructura interpretada no autoriza todavía una extrapolación estratégica específica.</p>`}${st.limits.length?`<div class="subhead">Límites</div>${list(st.limits.map(esc))}`:""}</div>`;}
function renderQuantStatus(a){const q=a.qualitative.quantification;$("#quantResult").innerHTML=`<h2>Cuantificación</h2><div class="card"><b>Nivel disponible desde este texto: ${esc(q.level)}</b><p>${esc(q.note)}</p>${q.variables.map(v=>`<div class="metric"><span>${esc(v.id)} · ${esc(v.label)}</span><b>${v.qualitative?"interpretable cualitativamente":"no identificada"} · ${v.numeric?"numérica":"sin valor puntual"}</b></div><div class="snippet">${esc(v.note)}</div>`).join("")}<p class="note">La ausencia de un valor numérico es una propiedad de la evidencia disponible, no una tarea pendiente del usuario. La sección de cuantificación opcional sólo permite incorporar datos adicionales cuando realmente existen.</p></div>`;}
function renderTrace(a){const g=a.game,top=a.concordance.slice(0,12);$("#technicalTrace").innerHTML=`<div class="metric"><span>Diccionario es_MX</span><b>${esc(a.dictionary.status)} · ${a.dictionary.size||0} entradas</b></div><div class="metric"><span>Frames</span><b>${a.semantic.frames.length} · UNRESOLVED ${a.semantic.stats.unresolved}</b></div><div class="metric"><span>Integridad semántica</span><b>no resueltos ${(a.semantic.integrity.unresolvedRatio*100).toFixed(0)}% · actor resuelto ${(a.semantic.integrity.resolvedActorRatio*100).toFixed(0)}%</b></div><div class="metric"><span>Episodios</span><b>${a.events.episodes.length}</b></div><div class="metric"><span>Catálogo estratégico</span><b>${g.catalogSize} plantillas</b></div>
 <h3>Entidades</h3>${a.entities.map(e=>`<div class="candidate"><b>${esc(e.name)}</b><span class="badge">${esc(e.type)}</span><div class="snippet">${esc(e.role||"—")} · menciones=${e.mentions.length} · ${esc(e.confidence)}</div></div>`).join("")||"<p class='note'>Sin entidades suficientes.</p>"}
 <h3>Concordancia</h3>${top.map(t=>`<div class="snippet"><b>${esc(t.term)}</b> f=${t.count} · relevancia=${t.relevance.toFixed(3)} · actores=${esc(t.actors.join(", ")||"—")}</div>`).join("")}
 <h3>Frames</h3>${a.semantic.frames.slice(0,80).map(f=>`<div class="candidate"><b>${esc(f.id)} · ${esc(f.type)}/${esc(f.sense||f.predicate||"—")}</b><span class="badge">${esc(f.realization)}</span><div class="snippet">actor=${esc(f.actor||"—")} · paciente=${esc(f.patient||"—")} · objeto=${esc(f.object||"—")}</div><div class="snippet">función=${esc(f.relation_to_event)} · epistemic=${esc(f.epistemic_status)}</div><div class="snippet">${esc(f.evidence)}</div></div>`).join("")}
 <h3>Episodios</h3>${a.events.episodes.map(e=>`<div class="candidate"><b>${esc(e.id)} · ${esc(e.family)}</b><span class="badge">${e.evidenceCount} evidencias</span></div>`).join("")}
 <h3>Juegos candidatos</h3><div class="candidate"><div class="snippet">Determinación canónica: ${g.determined?esc(g.determined.label):"indeterminada"}. Los requisitos declarados son duros.</div>${g.candidates.slice(0,10).map(x=>`<div class="snippet">${esc(x.label)} · compatibilidad=${x.score.toFixed(2)} · elegible=${x.eligible?"sí":"no"} · faltan=${esc(x.missing.join(", ")||"—")}</div>`).join("")}</div>
 <h3>Tracks</h3>${a.tracks.map(t=>`<div class="candidate"><b>${esc(t.label)}</b><div class="snippet">H=${esc(t.hLabel)} · actor=${esc(t.evaluatedActor||"no resuelto")} · operaciones comunicativas elegibles=${t.operations.length}</div></div>`).join("")}`;}
function renderAnalysis(a){lastQuantification=null;$("#status").className="card ok";$("#status").innerHTML=`<b>Análisis cualitativo completado</b><p>La semiótica se presenta como resultado principal. La mediación estratégica sólo extrapola estructuras sustentadas; la cuantificación permanece separada.</p>`;renderQualitative(a);renderStrategic(a);renderQuantStatus(a);renderTrace(a);$("#report").textContent=buildQualitativeReport(a,null);}
function populateScenarios(a){const s=$("#strategicScenario");s.innerHTML=`<option value="">estado observado</option>`+(a.game.scenarios||[]).map((x,i)=>`<option value="${i}">${esc(x.label)}</option>`).join("");}
async function analyzeText(){const raw=$("#corpus").value.trim();lastAnalysis=await ns.Analysis.analyze(raw);populateScenarios(lastAnalysis);renderAnalysis(lastAnalysis);return lastAnalysis;}
function setScale(track){$("#hLabel").value=track.hLabel||"";for(const k of ["0.00","0.25","0.50","0.75","1.00"]){const id={"0.00":"h0","0.25":"h25","0.50":"h50","0.75":"h75","1.00":"h100"}[k];$("#"+id).value=track.anchors?.[k]||"";}}
function actorRow(a){return `<tr><td><input value="${esc(a.id||"")}"></td><td><input value="${esc(a.role||"")}"></td><td><select class="hmode"><option value="${esc(a.hmode||"no")}">${esc(a.hmode||"no")}</option><option value="${a.hmode==="sí"?"no":"sí"}">${a.hmode==="sí"?"no":"sí"}</option></select></td><td><input type="number" step=".01" min="0" max="1" value="${inputVal(a.S)}"></td><td><input type="number" step=".01" min="0" max="1" value="${inputVal(a.E)}"></td><td><input type="number" step=".01" min="0" max="1" value="${inputVal(a.H)}"></td><td class="derived">—</td><td><textarea class="evS">${esc(a.evidence?.S||"")}</textarea><textarea class="evE">${esc(a.evidence?.E||"")}</textarea><textarea class="evH">${esc(a.evidence?.H||"")}</textarea></td><td><button class="smallbtn danger removeActor">×</button></td></tr>`;}
function opRow(o){return `<tr data-action-target="${esc(o.actionTarget||o.target||"")}" data-state-target="${esc(o.stateTarget||o.target||"")}" data-episode="${esc(o.episodeId||"")}" data-terminal-g=""><td><select class="source"></select></td><td><select class="target"></select></td><td><input class="optype" value="${esc(o.type||"")}"></td><td><input type="number" step=".01" min="0" max="1" value=""></td><td><input type="number" step=".01" min="0" max="1" value=""></td><td><input type="number" step=".01" min="0" max="1" value=""></td><td><textarea class="evD">${esc(o.evidence?.D||"")}</textarea><textarea class="evPhi">${esc(o.evidence?.phi||"")}</textarea><textarea class="evG">${esc(o.evidence?.G||"")}</textarea></td><td><button class="smallbtn danger removeOp">×</button></td></tr>`;}
function actorRows(){return $$("#actors tbody tr");}function opRows(){return $$("#ops tbody tr");}
function syncSelects(){const ids=actorRows().map(r=>r.querySelector("input").value.trim()).filter(Boolean),opts=ids.map(x=>`<option>${esc(x)}</option>`).join("");opRows().forEach(r=>{const s=r.querySelector(".source"),t=r.querySelector(".target"),sv=s.value||s.dataset.want||"",tv=t.value||t.dataset.want||"";s.innerHTML=opts;t.innerHTML=opts;if(ids.includes(sv))s.value=sv;if(ids.includes(tv))t.value=tv;});}
function selectedScenario(){if(!lastAnalysis)return null;const i=Number($("#strategicScenario").value);return Number.isInteger(i)&&i>=0?lastAnalysis.game.scenarios[i]:null;}
function prepareQuantification(){if(!lastAnalysis)throw new Error("Primero analice un texto.");const track=lastAnalysis.tracks.find(t=>t.operations.length)||lastAnalysis.tracks[0];if(!track)throw new Error("No existe un track interpretable.");$("#issue").value=lastAnalysis.scenario.issue;$("#scenarioNote").value=lastAnalysis.scenario.note;$("#issueMode").value=track.id;setScale(track);const actors=ns.Analysis.actorsForTrack(lastAnalysis,track),ops=ns.Analysis.operationsForTrack(lastAnalysis,track,selectedScenario());$("#actors tbody").innerHTML=actors.map(actorRow).join("");$("#ops tbody").innerHTML=ops.map(opRow).join("");syncSelects();opRows().forEach((r,i)=>{r.querySelector(".source").dataset.want=ops[i].source;r.querySelector(".target").dataset.want=ops[i].target;});syncSelects();refreshDerived();$("#partialResult").className="card";$("#partialResult").innerHTML=`<b>Variables preparadas</b><p>Los campos sin respaldo numérico permanecen vacíos. No es necesario completarlos para conservar el análisis cualitativo.</p>`;$("#quantPanel").open=true;}
function readActors(){return actorRows().map(r=>{const ins=r.querySelectorAll("input");return{id:ins[0].value.trim(),role:ins[1].value.trim(),hmode:r.querySelector(".hmode").value,S:num(ins[2].value),E:num(ins[3].value),H:num(ins[4].value),evidence:{S:r.querySelector(".evS").value.trim(),E:r.querySelector(".evE").value.trim(),H:r.querySelector(".evH").value.trim()}};});}
function readOperations(){const issue=$("#issue").value.trim();return opRows().map(r=>{const inputs=r.querySelectorAll('input[type="number"]'),rawTg=(r.dataset.terminalG||"").trim(),tg=rawTg===""?null:Number(rawTg);return{issue,source:r.querySelector(".source").value,target:r.querySelector(".target").value,actionTarget:r.dataset.actionTarget||r.querySelector(".target").value,stateTarget:r.dataset.stateTarget||r.querySelector(".target").value,episodeId:r.dataset.episode||"",terminalG:Number.isFinite(tg)?tg:null,type:r.querySelector(".optype").value.trim(),D:num(inputs[0].value),phi:num(inputs[1].value),G:num(inputs[2].value),evidence:{D:r.querySelector(".evD").value.trim(),phi:r.querySelector(".evPhi").value.trim(),G:r.querySelector(".evG").value.trim()}};});}
function valid01(v){return Number.isFinite(v)&&v>=0&&v<=1;}
function computePartial(){const actors=readActors(),ops=readOperations(),map=new Map(actors.map(a=>[a.id,a])),actorDerived=actors.map(a=>({id:a.id,R:valid01(a.S)&&valid01(a.E)?a.S*a.E:null,missing:[!valid01(a.S)?"S":null,!valid01(a.E)?"E":null].filter(Boolean)})),opDerived=[];for(const o of ops){const s=map.get(o.source),t=map.get(o.target);if(!s||!t){opDerived.push({source:o.source,target:o.target,status:"insuficiente",missing:["actor source/target"]});continue;}opDerived.push({...o,...ns.Core.partialInteraction(s,t,o)});}const complete=ops.length>0&&opDerived.length===ops.length&&opDerived.every(x=>x.status==="completo");let sequence=null;if(complete){const ids=new Set(ops.flatMap(o=>[o.source,o.target])),used=actors.filter(a=>ids.has(a.id));try{sequence=ns.Core.runSequence(used,ops);}catch(e){sequence={error:e.message};}}
 lastQuantification={actorDerived,operations:opDerived,complete,sequence};renderPartial(lastQuantification);if(lastAnalysis)$("#report").textContent=buildQualitativeReport(lastAnalysis,lastQuantification);return lastQuantification;}
function renderPartial(q){const actors=q.actorDerived.filter(x=>Number.isFinite(x.R)),ops=q.operations.filter(x=>[x.R,x.X,x.gap,x.deltaH].some(Number.isFinite)),any=actors.length||ops.length;$("#partialResult").className=`card ${q.complete?"ok":""}`;if(!any){$("#partialResult").innerHTML=`<b>Sin magnitudes numéricas sustentadas</b><p>El análisis cualitativo permanece completo. No se enumeran parámetros vacíos ni se exige al usuario completarlos.</p>`;return;}$("#partialResult").innerHTML=`<b>${q.complete?"Cálculo completo disponible":"Cálculo parcial"}</b><p>Se muestran sólo componentes realmente derivables.</p>${actors.map(x=>`<div class="metric"><span>${esc(x.id)} · R=S×E</span><b>${fmt(x.R)}</b></div>`).join("")}${ops.map((x,i)=>`<div class="candidate"><strong>Componente ${i+1}: ${esc(x.source||"—")} → ${esc(x.target||"—")}</strong><div class="snippet">R=${fmt(x.R)} · X=${fmt(x.X)} · gap=${fmt(x.gap)} · ΔH=${fmt(x.deltaH)} · dirección=${esc(x.direction||"indeterminada")}</div></div>`).join("")}${q.complete&&q.sequence&&!q.sequence.error?`<div class="subhead">Trayectoria secuencial completa</div>${q.sequence.history.map((r,i)=>`<div class="snippet">${i+1}. ${esc(r.source)}→${esc(r.target)} · H ${fmt(r.Hbefore)}→${fmt(r.Hafter)} · ΔH=${fmt(r.deltaH)}</div>`).join("")}`:""}`;}
function hScale(){return{label:$("#hLabel").value.trim(),anchors:{"0.00":$("#h0").value.trim(),"0.25":$("#h25").value.trim(),"0.50":$("#h50").value.trim(),"0.75":$("#h75").value.trim(),"1.00":$("#h100").value.trim()}};}
function buildQualitativeReport(a,q){const s=a.semiotic,st=a.qualitative.strategic,lines=["REPORTE DE ANÁLISIS — LIMES v0.54","==================================","","1. ANÁLISIS CUALITATIVO",`Dominio: ${a.events.domain.label} · confianza=${a.events.domain.score.toFixed(2)}`,`Issue: ${a.scenario.issue}`,`Lectura: ${a.qualitative.analysisSummary||"—"}`];lines.push("","1.1 Actores y configuración");s.actors.slice(0,10).forEach(x=>{lines.push(`- ${x.id} | ${x.role||x.type}`);if(x.ser.length)lines.push(`  Ser: ${x.ser[0]}`);if(x.estar.length)lines.push(`  Estar: ${x.estar[0]}`);if(x.decir.length)lines.push(`  Decir: ${x.decir[0]}`);if(x.hacer.length)lines.push(`  Hacer: ${x.hacer[0]}`);});lines.push("","1.2 Objetos de valor / disputa");if(s.valueObjects.length)s.valueObjects.forEach(o=>lines.push(`- ${o.object} | tipo=${o.kind||"objeto"} | actores=${o.actors.join(", ")||"—"} | evidencias=${o.count}`));else lines.push("- No suficientemente identificados.");lines.push("","1.3 Oposiciones");if(s.oppositions.length)s.oppositions.forEach(o=>lines.push(`- ${o.left} ↔ ${o.right} [${o.status}]`));else lines.push("- No suficientemente identificadas.");lines.push("","1.4 Programas / contra-programas");s.programs.forEach(p=>lines.push(`- ${p.id} · ${p.label||"Programa"}: ${p.actor} | ${p.orientation} | objetivo=${p.goal||p.object||"—"} | acciones=${p.actions.join(", ")||"—"}`));s.counterPrograms.forEach(c=>lines.push(`- ${c.a} ↔ ${c.b}: ${c.actors.join(" / ")} | ${c.object||"—"}`));lines.push("","1.5 Fronteras");if(s.frontiers.length)s.frontiers.forEach(f=>lines.push(`- ${f.source} → ${f.target} | ${f.kind} | ${f.condition}`));else lines.push("- No suficientemente identificadas.");
 lines.push("","2. MEDIACIÓN ESTRATÉGICA",`Estructura: ${st.label} [${st.status}]`);st.basis.forEach(x=>lines.push(`- Base: ${x}`));if(st.scenarios.length){lines.push("","2.1 Extrapolación cualitativa");st.scenarios.forEach((x,i)=>{lines.push(`${i+1}. ${x.label}`);lines.push(`   ${x.projection}`);lines.push(`   Base: ${x.basis}`);lines.push(`   Límite: ${x.limit}`);});}else lines.push("Extrapolación específica: no autorizada por la estructura disponible.");if(st.limits.length){lines.push("","2.2 Límites");st.limits.forEach(x=>lines.push(`- ${x}`));}
 lines.push("","3. CUANTIFICACIÓN SELECTIVA");a.qualitative.quantification.variables.forEach(v=>lines.push(`- ${v.id} ${v.label}: ${v.qualitative?"interpretable cualitativamente":"no identificada"}; valor puntual=${v.numeric?"sí":"no"}. ${v.note}`));if(q){const qa=q.actorDerived.filter(x=>Number.isFinite(x.R)),qo=q.operations.filter(x=>[x.R,x.X,x.gap,x.deltaH].some(Number.isFinite));if(qa.length||qo.length){lines.push("","3.1 Componentes numéricos sustentados");qa.forEach(x=>lines.push(`- ${x.id}: R=${fmt(x.R)}`));qo.forEach((x,i)=>lines.push(`- Componente ${i+1}: R=${fmt(x.R)} X=${fmt(x.X)} gap=${fmt(x.gap)} ΔH=${fmt(x.deltaH)} dirección=${x.direction||"indeterminada"}`));}else lines.push("- No hay componentes numéricos sustentados por esta fuente; no se muestran parámetros vacíos.");}else lines.push("- No se ejecutó cuantificación numérica. Esto no invalida el análisis cualitativo.");
 lines.push("","4. ANEXO TÉCNICO",`Entidades: ${a.entities.length}`,`Frames: ${a.semantic.frames.length} · UNRESOLVED=${a.semantic.stats.unresolved}`,`Episodios: ${a.events.episodes.length}`,`Juegos catalogados: ${a.game.catalogSize}`,`Juego canónico determinado: ${a.game.determined?a.game.determined.label:"no"}`,"","Nota metodológica: la semiótica precede a la mediación estratégica. La teoría de juegos sólo organiza lo que ya fue interpretado y únicamente permite extrapolar ramas sustentadas. La cuantificación es selectiva; el núcleo v0.40 calcula R, X y ΔH sólo con variables numéricas justificadas.");return lines.join("\n");}
function refreshDerived(){const A=readActors();actorRows().forEach((r,i)=>{const a=A[i];r.querySelector(".derived").textContent=a&&valid01(a.S)&&valid01(a.E)?(a.S*a.E).toFixed(3):"—";});syncSelects();}
function addActor(){$("#actors tbody").insertAdjacentHTML("beforeend",actorRow({id:"",role:"",hmode:"no",S:null,E:null,H:null,evidence:{S:"",E:"",H:""}}));refreshDerived();}
function addOp(){const o={source:"",target:"",actionTarget:"",stateTarget:"",type:"",D:null,phi:null,G:null,evidence:{D:"",phi:"",G:""}};$("#ops tbody").insertAdjacentHTML("beforeend",opRow(o));syncSelects();}
function download(name,content,type){const b=new Blob([content],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href);}
$("#analyzeText").onclick=async()=>{try{await analyzeText();}catch(e){$("#status").className="card warn";$("#status").innerHTML=`<b>Análisis no disponible</b><p>${esc(e.message)}</p>`;}};
$("#loadTextEvidence").onclick=()=>{try{prepareQuantification();}catch(e){$("#partialResult").className="card warn";$("#partialResult").innerHTML=`<b>Cuantificación no preparada</b><p>${esc(e.message)}</p>`;}};
$("#addActor").onclick=addActor;$("#addOp").onclick=addOp;$("#actors").addEventListener("input",refreshDerived);$("#actors").addEventListener("click",e=>{if(e.target.classList.contains("removeActor")){e.target.closest("tr").remove();refreshDerived();}});$("#ops").addEventListener("click",e=>{if(e.target.classList.contains("removeOp")){e.target.closest("tr").remove();refreshDerived();}});$("#run").onclick=()=>{try{computePartial();}catch(e){$("#partialResult").className="card warn";$("#partialResult").innerHTML=`<b>Cuantificación no disponible</b><p>${esc(e.message)}</p>`;}};
$("#exportTxt").onclick=()=>{if(!lastAnalysis){alert("Primero analice un texto.");return;}download("Limes_v054_reporte.txt",buildQualitativeReport(lastAnalysis,lastQuantification),"text/plain;charset=utf-8");};
$("#exportJson").onclick=()=>{if(!lastAnalysis){alert("Primero analice un texto.");return;}download("Limes_v054_analisis.json",JSON.stringify({analysis:lastAnalysis,quantification:lastQuantification},null,2),"application/json;charset=utf-8");};
$("#jscheck").className="card ok";$("#jscheck").innerHTML=`<b>Módulos activos</b><p>v0.54 · semiótica cualitativa · mediación estratégica · cuantificación selectiva · Core v0.40 · ${ns.GameOntology.count} juegos catalogados.</p>`;
ns.App={analyzeText,prepareQuantification,computePartial,buildQualitativeReport,get lastAnalysis(){return lastAnalysis;},get lastQuantification(){return lastQuantification;}};
})(window);
