"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
const ORG_HEADS=["Fiscalía","Fiscalia","Gobierno","Gobernación","Gobernacion","Congreso","Policía","Policia","Agencia","Universidad","Secretaría","Secretaria","Ayuntamiento","Tribunal","Juzgado","Corte","Instituto","Sindicato","Asociación","Asociacion","Comunidad","Consejo","Comisión","Comision","Partido","Ministerio","Procuraduría","Procuraduria","Oficina","Servicio","Administración","Administracion","Cártel","Cartel"];
const LAW_HEADS=["Ley","Código","Codigo","Reglamento","Constitución","Constitucion","Decreto","Norma"];
const BAD_INITIAL=new Set(`control federal pero por para y e o u si no como cómo cuando mientras aunque porque entonces luego también tambien además ademas dijo dijeron corrió corrio volcó volco indicó indico indicaron aseguró aseguro aseguraron agregó agrego agregaron respondió respondio señaló senalo anunció anuncio según segun durante al en del la el los las un una dios míos mios hola anda`.split(/\s+/));
const HUMAN_COLLECTIVE_HEADS=new Set(`autoridades niños niñas migrantes comerciantes taxistas trabajadores trabajadoras estudiantes ciudadanos ciudadanas vecinos vecinas huéspedes huespedes policías policias agentes legisladores legisladoras diputados diputadas senadores senadoras padres madres familias manifestantes organizaciones comunidades colectivos usuarios usuarias profesionales funcionarios funcionarias empleados empleadas productores productoras empresarios empresarias académicos academicos investigadores investigadoras pacientes docentes consumidores consumidoras electores votantes`.split(/\s+/));
const ANIMAL_HEADS=new Set(`pájaros pajaros fieras lobos aves patos patitos animales ratones`.split(/\s+/));
const NON_AGENT_NOUNS=new Set(`bolsillo bolsillos ojo ojos tema temas camino caminos noche noches preocupacion preocupaciones dato datos hecho hechos declaración declaraciones evidencia evidencias información informaciones pan piedras piedra fuego casa bosque agua mesa mesas propuesta propuestas medida medidas restricción restricciones norma normas ley leyes documento documentos informe informes expediente expedientes recurso recursos resultado resultados objetivo objetivos`.split(/\s+/));
const PROGRAM_DAYS="Lunes|Martes|Miércoles|Miercoles|Jueves|Viernes|Sábado|Sabado|Domingo";
function cleanSurface(s){return String(s||"").replace(/^[“"'¿¡\s]+|[”"'.,;:!?\s]+$/g,"").replace(/\s+/g," ").trim();}
function canonicalKey(s){return ns.Spanish.strip(cleanSurface(s)).replace(/\s+/g," ");}
function add(map,name,type,role,mention,index,confidence="media",aliases=[]){name=cleanSurface(name);if(!name)return;const key=canonicalKey(name);if(!key)return;let e=map.get(key);if(!e){e={name,type,role:role||"",aliases:[...aliases],mentions:[],confidence,operationalCandidate:!["PLACE","LAW","PROGRAM","EVENT","DEITY"].includes(type)};map.set(key,e);}if(mention)e.mentions.push({surface:mention,index});for(const a of aliases)if(a&&!e.aliases.includes(a))e.aliases.push(a);return e;}
function overlaps(a,b){return a.start<b.end&&b.start<a.end;}
function detectInstitutional(raw,map,spans){
 const head=ORG_HEADS.map(x=>x.replace(/\s+/g,"\\s+")).join("|");
 const rx=new RegExp(`\\b(?:${head})(?:\\s+(?:General|Especial|Especializada|Federal|Nacional|Estatal|Municipal|de|del|la|las|los|y|e|para|en|Control|Investigación|Investigacion|Justicia|República|Republica|Ciudad|México|Mexico|Regional|Ministerial|Criminal|Migración|Migracion|Aduanas|Fronteras|[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ-]+)){0,10}`,'gu');
 let m;while((m=rx.exec(raw))){let surface=cleanSurface(m[0]).replace(/\s+(de|del|la|las|los|y|e|para|en)$/i,"");if(/^Gobernaci[oó]n\s+(?!de\b)/i.test(surface))surface=surface.split(/\s+/)[0];if(!surface)continue;let type=/Gobierno|Gobernación|Gobernacion|Ayuntamiento|Congreso|Secretar|Ministerio|Consejo|Comisión|Comision/.test(surface)?"GOVERNMENT":"INSTITUTION";if(/Polic|Agencia/.test(surface))type="ORGANIZATION";const role=type==="GOVERNMENT"?"autoridad pública":/Fiscal|Polic|Agencia|Procur/.test(surface)?"institución de investigación/seguridad":"institución/organización";add(map,surface,type,role,surface,m.index,"media-alta");spans.push({start:m.index,end:m.index+surface.length});}
 const ac=/\b[A-ZÁÉÍÓÚÑ]{2,10}\b/g;while((m=ac.exec(raw))){const s=m[0];if(["CDMX","EU","EEUU"].includes(s))continue;const before=raw.slice(Math.max(0,m.index-160),m.index),after=raw.slice(m.index+s.length,m.index+s.length+70).trim(),next=(after.match(/^([\p{L}áéíóúñ-]+)/u)||[])[1]||"";const institutionalContext=/\b(?:Fiscalía|Fiscalia|Policía|Policia|Agencia|Universidad|Secretaría|Secretaria|Instituto|Organización|Organizacion|Oficina|Administración|Administracion|Ministerio|Consejo|Comisión|Comision|Autoridad|Servicio|Departamento|Dirección|Direccion)\b/i.test(before);const subjectUse=next&&ns.Spanish.isLikelyFiniteVerb(next);if(institutionalContext||subjectUse){add(map,s,"INSTITUTION","sigla institucional",s,m.index,institutionalContext?"media-alta":"media");spans.push({start:m.index,end:m.index+s.length});}}
}
function detectLaws(raw,map,spans){const head=LAW_HEADS.join("|");const rx=new RegExp(`\\b(?:${head})(?:\\s+(?:de|del|la|las|los|y|e|para|en|[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ]+)){1,10}`,'gu');let m;while((m=rx.exec(raw))){let s=cleanSurface(m[0]).replace(/\s+(de|del|la|las|los|y|e|para|en)$/i,"");add(map,s,"LAW","instrumento normativo",s,m.index,"alta");spans.push({start:m.index,end:m.index+m[0].length});}}
function detectPlaces(raw,map,spans){const rx=/\b(?:Ciudad de|Estado de|Municipio de|República de)\s+[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ]+(?:\s+(?:de|del|la|las|los|y|[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ]+)){0,5}/gu;let m;while((m=rx.exec(raw))){add(map,m[0],"PLACE","lugar / contexto",m[0],m.index,"alta");spans.push({start:m.index,end:m.index+m[0].length});}const common=/\b(?:Estados Unidos|México|Mexico)\b/gu;while((m=common.exec(raw))){add(map,m[0],"PLACE","lugar / contexto",m[0],m.index,"alta");spans.push({start:m.index,end:m.index+m[0].length});}}
function detectDeities(raw,map,spans){const rx=/\b(?:Dios(?:\s+Nuestro\s+Señor)?|Nuestro\s+Señor)\b/gu;let m;while((m=rx.exec(raw))){add(map,m[0],"DEITY","referente religioso no asumido como actor operativo",m[0],m.index,"alta");spans.push({start:m.index,end:m.index+m[0].length});}}
function detectPrograms(raw,map,spans){const rx=new RegExp(`\\b(?:(?:Programa|Plan|Operativo|Jornada|Foro)\\s+[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ-]+(?:\\s+[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ-]+){0,4}|(?:${PROGRAM_DAYS})\\s+[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ-]+)\\b`,'gu');let m;while((m=rx.exec(raw))){const s=cleanSurface(m[0]);add(map,s,"PROGRAM","programa/evento institucional",s,m.index,"media-alta");spans.push({start:m.index,end:m.index+m[0].length});}}
function detectPersons(raw,map,spans){
 let idm;const identity=[/\b(?:el|la)\s+(?:niño|niña|muchacho|muchacha)\s+se\s+llamaba\s+([A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+)/gu,/\b(?:y\s+)?(?:el|la)\s+(?:niño|niña|muchacho|muchacha)\s*,\s*([A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+)/gu];for(const rxid of identity)while((idm=rxid.exec(raw)))add(map,idm[1],"PERSON","persona/personaje identificado por el texto",idm[1],idm.index+idm[0].lastIndexOf(idm[1]),"alta");
 const chars=[...raw];for(const sp of spans)for(let i=sp.start;i<Math.min(sp.end,chars.length);i++)chars[i]=" ";const masked=chars.join("");
 const rx=/\b[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+(?:\s+(?:[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+|de|del|la|las|los)){1,4}(?=$|[^\p{L}áéíóúñ'-])/gu;let m;
 while((m=rx.exec(masked))){const surface=cleanSurface(raw.slice(m.index,m.index+m[0].length)),parts=surface.split(/\s+/),first=parts[0];if(BAD_INITIAL.has(ns.Spanish.strip(first))||ns.Spanish.isLikelyFiniteVerb(first))continue;const lexical=parts.filter(x=>!/^(de|del|la|las|los)$/i.test(x));if(lexical.length<2)continue;const context=raw.slice(Math.max(0,m.index-60),Math.min(raw.length,m.index+m[0].length+60)),personCue=/\b(president[ae]|doctor|doctora|señor|señora|sr\.?|sra\.?|juez|integrante|hijo|hija|fundador|rector|diputad[oa]|senador[oa]|gobernador[ae]|titular)\b/i.test(context);if(!personCue&&ns.Spanish.inDictionary(first)&&ns.Spanish.inDictionary(lexical[1]))continue;add(map,surface,"PERSON","persona",surface,m.index,personCue?"alta":"media");}
 const single=/\b[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]{2,}(?=$|[^\p{L}áéíóúñ'-])/gu,counts=new Map(),hits=[];while((m=single.exec(masked))){const s=raw.slice(m.index,m.index+m[0].length),key=ns.Spanish.strip(s);if(BAD_INITIAL.has(key)||ns.Spanish.isLikelyFiniteVerb(s)||ns.Spanish.inDictionary(s))continue;counts.set(s,(counts.get(s)||0)+1);hits.push({s,index:m.index});}for(const h of hits){const cue=raw.slice(Math.max(0,h.index-35),h.index),after=raw.slice(h.index+h.s.length,h.index+h.s.length+40).trim(),next=(after.match(/^([\p{L}áéíóúñ-]+)/u)||[])[1]||"";if((counts.get(h.s)||0)>=2||/\b(dijo|respondió|respondio|exclamó|exclamo|llamaba|llamado|llamada|preguntó|pregunto)\s*$/i.test(cue)||(next&&ns.Spanish.isLikelyFiniteVerb(next)))add(map,h.s,"PERSON","persona/personaje",h.s,h.index,"media");}
}
function sentenceBounds(raw,index){let a=Math.max(raw.lastIndexOf(".",index),raw.lastIndexOf("\n",index),raw.lastIndexOf(";",index));a=a<0?0:a+1;let ends=[raw.indexOf(".",index),raw.indexOf("\n",index),raw.indexOf(";",index)].filter(x=>x>=0);let b=ends.length?Math.min(...ends):raw.length;return [a,b];}
function detectCollectives(raw,map){const rx=/\b(?:los|las)\s+([a-záéíóúñ][\p{L}áéíóúñ-]{3,})(?:\s+([a-záéíóúñ][\p{L}áéíóúñ-]{3,}))?/giu;let m;while((m=rx.exec(raw))){let words=[m[1],m[2]].filter(Boolean);if(words.length>1&&ns.Spanish.isLikelyFiniteVerb(words[1]))words=words.slice(0,1);const phrase=cleanSurface(raw.slice(m.index,m.index+(m[0].indexOf(m[1])+words.join(" ").length))),normWords=words.map(ns.Spanish.strip),head=normWords[0]||"";if(normWords.some(w=>NON_AGENT_NOUNS.has(w))||normWords.some(w=>ns.Spanish.isLikelyFiniteVerb(w))||/^(estamos|estaban|han|hemos|habian|habían)$/.test(head))continue;if(ANIMAL_HEADS.has(head)){add(map,phrase,"EVENT","agente ambiental/no estratégico",phrase,m.index,"media");continue;}const morphAgent=/(?:dores|doras|antes|istas|arios|arias|eros|eras|entes|anos|anas|inos|inas)$/.test(head),agentive=HUMAN_COLLECTIVE_HEADS.has(head)||morphAgent;if(!agentive)continue;const [a,b]=sentenceBounds(raw,m.index),before=raw.slice(a,m.index),localBefore=before.split(/[,;:]/).pop()||before,after=raw.slice(m.index+phrase.length,b).trim(),beforeHasPredicate=ns.Spanish.tokenize(localBefore).some(t=>ns.Spanish.BASE_VERBS.includes(t.lemma)),afterTokens=ns.Spanish.tokenize(after).slice(0,6),subjectLike=!beforeHasPredicate&&afterTokens.some(t=>ns.Spanish.isLikelyFiniteVerb(t.surface)),repeated=(raw.match(new RegExp(`\\b${phrase.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}\\b`,'gi'))||[]).length>=2;if(subjectLike||repeated)add(map,phrase,"COLLECTIVE","colectivo textual",phrase,m.index,subjectLike?"media-alta":"media");}}
function detectRoleEntities(raw,map){const roles={"padre":"PERSON_ROLE","madre":"PERSON_ROLE","madrastra":"PERSON_ROLE","padrastro":"PERSON_ROLE","hombre":"PERSON_ROLE","mujer":"PERSON_ROLE","leñador":"PERSON_ROLE","niño":"PERSON_ROLE","niña":"PERSON_ROLE","hermano":"PERSON_ROLE","hermana":"PERSON_ROLE","viejo":"PERSON_ROLE","vieja":"PERSON_ROLE","bruja":"PERSON_ROLE","rey":"PERSON_ROLE","reina":"PERSON_ROLE","juez":"COURT_ROLE","testigo":"PERSON_ROLE","investigado":"PERSON_ROLE","acusado":"PERSON_ROLE","víctima":"PERSON_ROLE","victima":"PERSON_ROLE"};for(const [word,type] of Object.entries(roles)){const rx=new RegExp(`\\b${word}\\b`,'gi'),hits=[...raw.matchAll(rx)];if(!hits.length)continue;const role=type==="COURT_ROLE"?"rol judicial":"rol textual";for(const m of hits)add(map,word,type,role,m[0],m.index,"media");}}
function mergeAliases(list){const removed=new Set(),mergeable=new Set(["PERSON","GOVERNMENT","INSTITUTION","ORGANIZATION","COLLECTIVE","LAW","PROGRAM"]);for(let i=0;i<list.length;i++){if(removed.has(i))continue;for(let j=0;j<list.length;j++){if(i===j||removed.has(j))continue;const a=list[i],b=list[j];if(a.type!==b.type||!mergeable.has(a.type))continue;const ka=canonicalKey(a.name),kb=canonicalKey(b.name),contained=ka.includes(kb)||kb.includes(ka);if(contained){const keep=a.name.length>=b.name.length?a:b,drop=keep===a?b:a,kd=keep===a?j:i;if(drop.name!==keep.name&&!keep.aliases.includes(drop.name))keep.aliases.push(drop.name);keep.mentions.push(...drop.mentions);removed.add(kd);if(kd===i)break;}}}return list.filter((_,i)=>!removed.has(i));}
function linkAcronyms(raw,list){const removed=new Set();for(let i=0;i<list.length;i++){const e=list[i];if(!["INSTITUTION","GOVERNMENT","ORGANIZATION"].includes(e.type))continue;for(let j=0;j<list.length;j++){if(i===j||removed.has(j))continue;const a=list[j];if(!/^[A-ZÁÉÍÓÚÑ]{2,10}$/.test(a.name))continue;const rx=new RegExp(e.name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"\\s*\\("+a.name+"\\)","i");if(rx.test(raw)){if(!e.aliases.includes(a.name))e.aliases.push(a.name);e.mentions.push(...a.mentions);removed.add(j);}}}return list.filter((_,i)=>!removed.has(i));}
function linkNarrativeIdentity(raw,list){const removed=new Set();function bind(role,name){const r=list.findIndex(e=>e.type==="PERSON_ROLE"&&canonicalKey(e.name)===canonicalKey(role)),p=list.findIndex(e=>e.type==="PERSON"&&canonicalKey(e.name)===canonicalKey(name));if(r<0||p<0||r===p)return;if(!list[p].aliases.includes(list[r].name))list[p].aliases.push(list[r].name);list[p].mentions.push(...list[r].mentions);removed.add(r);}let m;const rx=/\b(?:el|la)\s+(niño|niña|muchacho|muchacha)\s+se\s+llamaba\s+([A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+)/giu;while((m=rx.exec(raw)))bind(m[1],m[2]);const ell=/\b(?:y\s+)?(?:el|la)\s+(niño|niña|muchacho|muchacha)\s*,\s*([A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+)/giu;while((m=ell.exec(raw)))bind(m[1],m[2]);return list.filter((_,i)=>!removed.has(i));}
function detect(raw){const map=new Map(),spans=[];detectInstitutional(raw,map,spans);detectLaws(raw,map,spans);detectPrograms(raw,map,spans);detectPlaces(raw,map,spans);detectDeities(raw,map,spans);detectPersons(raw,map,spans);detectCollectives(raw,map);detectRoleEntities(raw,map);let out=linkNarrativeIdentity(raw,linkAcronyms(raw,mergeAliases([...map.values()])));out.forEach(e=>{e.aliases=[...new Set(e.aliases)];e.mentions=e.mentions.sort((a,b)=>a.index-b.index);});return out.sort((a,b)=>b.mentions.length-a.mentions.length||a.name.localeCompare(b.name,"es"));}
function mentionsIn(text,entities){const n=ns.Spanish.strip(text),out=[];for(const e of entities){const forms=[e.name,...e.aliases].filter(Boolean);if(forms.some(f=>n.includes(ns.Spanish.strip(f))))out.push(e.name);}return [...new Set(out)];}
ns.Entities={detect,mentionsIn,canonicalKey};
})(window);
