"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
const ORG_HEADS=["Fiscalía","Fiscalia","Gobierno","Congreso","Policía","Policia","Agencia","Universidad","Secretaría","Secretaria","Ayuntamiento","Tribunal","Juzgado","Corte","Instituto","Sindicato","Asociación","Asociacion","Comunidad","Consejo","Comisión","Comision","Partido","Ministerio","Procuraduría","Procuraduria","Fiscalía Especial","Fiscalia Especial","Cártel","Cartel"];
const LAW_HEADS=["Ley","Código","Codigo","Reglamento","Constitución","Constitucion","Decreto","Norma"];
const BAD_INITIAL=new Set(["Control","Federal","Pero","Por","Para","Y","E","O","U","Si","No","Como","Cuando","Mientras","Aunque","Porque","Entonces","Luego","Dijo","Dijeron","Corrió","Corrio","Volcó","Volco","Indicó","Indico","Indicaron","Aseguró","Aseguro","Aseguraron","Agregó","Agrego","Agregaron","Respondió","Respondio","Señaló","Senalo","Anunció","Anuncio","Según","Segun","Durante","Al","En","Del","La","El","Los","Las","Un","Una","Dios"]);
function cleanSurface(s){return String(s||"").replace(/^[“"'¿¡\s]+|[”"'.,;:!?\s]+$/g,"").replace(/\s+/g," ").trim();}
function canonicalKey(s){return ns.Spanish.strip(cleanSurface(s)).replace(/\s+/g," ");}
function add(map,name,type,role,mention,index,confidence="media",aliases=[]){name=cleanSurface(name);if(!name)return;const key=canonicalKey(name);if(!key)return;let e=map.get(key);if(!e){e={name,type,role:role||"",aliases:[...aliases],mentions:[],confidence,operationalCandidate:!["PLACE","LAW","PROGRAM","EVENT"].includes(type)};map.set(key,e);}if(mention)e.mentions.push({surface:mention,index});for(const a of aliases)if(a&&!e.aliases.includes(a))e.aliases.push(a);return e;}
function overlaps(a,b){return a.start<b.end&&b.start<a.end;}
function detectInstitutional(raw,map,spans){
 const head=ORG_HEADS.map(x=>x.replace(/\s+/g,"\\s+")).join("|");
 const rx=new RegExp(`\\b(?:${head})(?:\\s+(?:General|Especial|Especializada|Federal|Nacional|Estatal|Municipal|de|del|la|las|los|y|e|para|en|Control|Investigación|Investigacion|Justicia|República|Republica|Ciudad|México|Mexico|Regional|Ministerial|Criminal|[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ-]+)){0,10}`,'gu');
 let m;while((m=rx.exec(raw))){let surface=cleanSurface(m[0]);surface=surface.replace(/\s+(de|del|la|las|los|y|e|para|en)$/i,"");if(surface.split(/\s+/).length<1)continue;let type=/Gobierno|Ayuntamiento|Congreso|Secretar|Ministerio|Consejo|Comisión|Comision/.test(surface)?"GOVERNMENT":"INSTITUTION";if(/Polic|Agencia/.test(surface))type="ORGANIZATION";const role=type==="GOVERNMENT"?"autoridad pública":/Fiscal|Polic|Agencia|Procur/.test(surface)?"institución de investigación/seguridad":"institución/organización";add(map,surface,type,role,surface,m.index,"media-alta");spans.push({start:m.index,end:m.index+m[0].length});}
 const ac=/\b[A-ZÁÉÍÓÚÑ]{2,10}\b/g;while((m=ac.exec(raw))){const s=m[0];if(["CDMX","EU","EEUU"].includes(s))continue;const prev=raw.slice(Math.max(0,m.index-120),m.index);if(/\b(?:Fiscalía|Fiscalia|Policía|Policia|Agencia|Universidad|Secretaría|Secretaria|Instituto|Organización|Organizacion|Interpol)\b[^.]{0,100}$/i.test(prev)){add(map,s,"INSTITUTION","sigla institucional",s,m.index,"media");spans.push({start:m.index,end:m.index+s.length});}}
}
function detectLaws(raw,map,spans){const head=LAW_HEADS.join("|");const rx=new RegExp(`\\b(?:${head})(?:\\s+(?:de|del|la|las|los|y|e|para|en|[A-ZÁÉÍÓÚÑ][\\p{L}áéíóúñ]+)){1,10}`,'gu');let m;while((m=rx.exec(raw))){let s=cleanSurface(m[0]).replace(/\s+(de|del|la|las|los|y|e|para|en)$/i,"");add(map,s,"LAW","instrumento normativo",s,m.index,"alta");spans.push({start:m.index,end:m.index+m[0].length});}}
function detectPlaces(raw,map,spans){const rx=/\b(?:Ciudad de|Estado de|Municipio de|República de)\s+[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ]+(?:\s+(?:de|del|la|las|los|y|[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ]+)){0,5}/gu;let m;while((m=rx.exec(raw))){add(map,m[0],"PLACE","lugar / contexto",m[0],m.index,"alta");spans.push({start:m.index,end:m.index+m[0].length});}}
function detectPersons(raw,map,spans){
 const rx=/\b[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+(?:\s+(?:[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]+|de|del|la|las|los)){1,4}\b/gu;let m;
 while((m=rx.exec(raw))){const surface=cleanSurface(m[0]),parts=surface.split(/\s+/),first=parts[0];if(BAD_INITIAL.has(first)||ns.Spanish.isLikelyFiniteVerb(first))continue;if(spans.some(s=>overlaps({start:m.index,end:m.index+m[0].length},s)))continue;if(/^(?:Fiscalía|Fiscalia|Gobierno|Congreso|Policía|Policia|Agencia|Universidad|Secretaría|Secretaria|Ayuntamiento|Tribunal|Juzgado|Corte|Instituto|Sindicato|Asociación|Asociacion|Comunidad|Consejo|Comisión|Comision|Ley|Código|Codigo|Reglamento|Constitución|Constitucion)\b/.test(surface))continue;
  // At least two lexical name tokens, and first token should not be an ordinary dictionary word when available unless honorific/context says person.
  const lexical=parts.filter(x=>!/^(de|del|la|las|los)$/i.test(x));if(lexical.length<2)continue;const context=raw.slice(Math.max(0,m.index-50),Math.min(raw.length,m.index+m[0].length+50));const personCue=/\b(president[ae]|doctor|doctora|señor|señora|sr\.?|sra\.?|juez|integrante|hijo|hija|fundador|rector|diputad[oa]|senador[oa]|gobernador[ae])\b/i.test(context);
  if(!personCue&&ns.Spanish.inDictionary(first)&&ns.Spanish.inDictionary(lexical[1]))continue;
  add(map,surface,"PERSON","persona",surface,m.index,personCue?"alta":"media");spans.push({start:m.index,end:m.index+m[0].length});
 }
 // Single proper names repeated or used after a speech/action cue.
 const single=/\b[A-ZÁÉÍÓÚÑ][\p{L}áéíóúñ'-]{2,}\b/gu;const counts=new Map(),hits=[];while((m=single.exec(raw))){const s=m[0];if(BAD_INITIAL.has(s)||ns.Spanish.isLikelyFiniteVerb(s)||spans.some(x=>m.index>=x.start&&m.index<x.end))continue;counts.set(s,(counts.get(s)||0)+1);hits.push({s,index:m.index});}
 for(const h of hits){const cue=raw.slice(Math.max(0,h.index-25),h.index);if((counts.get(h.s)||0)>=2||/\b(dijo|respondió|respondio|exclamó|exclamo|llamaba|llamado|llamada)\s*$/i.test(cue)){add(map,h.s,"PERSON","persona/personaje",h.s,h.index,"media");}}
}
function detectCollectives(raw,map){const rx=/\b(?:los|las)\s+([a-záéíóúñ][\p{L}áéíóúñ-]{3,})(?:\s+([a-záéíóúñ][\p{L}áéíóúñ-]{3,}))?/giu;let m;while((m=rx.exec(raw))){const phrase=cleanSurface(m[0]),noun=cleanSurface([m[1],m[2]].filter(Boolean).join(" "));if(ns.Spanish.STOP.has(ns.Spanish.strip(noun))||/^(hechos?|investigaciones?|circunstancias?|datos?|declaraciones?|implicaciones?|noches?|barrios?)$/i.test(noun))continue;const contexts=(raw.match(new RegExp(`\\b${phrase.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'gi'))||[]).length;if(contexts>=2||/rechaz|pid|exhort|protest|demand|organiza|represent/.test(ns.Spanish.strip(raw.slice(Math.max(0,m.index-80),m.index+180))))add(map,phrase,"COLLECTIVE","colectivo textual",phrase,m.index,"media");}}

function detectRoleEntities(raw,map){const roles={"padre":"PERSON_ROLE","madre":"PERSON_ROLE","madrastra":"PERSON_ROLE","padrastro":"PERSON_ROLE","bruja":"PERSON_ROLE","rey":"PERSON_ROLE","reina":"PERSON_ROLE","juez":"COURT_ROLE","testigo":"PERSON_ROLE","investigado":"PERSON_ROLE","acusado":"PERSON_ROLE","víctima":"PERSON_ROLE","victima":"PERSON_ROLE"};for(const [word,type] of Object.entries(roles)){const rx=new RegExp(`\\b${word}\\b`,'gi'),hits=[...raw.matchAll(rx)];if(!hits.length)continue;const role=type==="COURT_ROLE"?"rol judicial":"rol textual";for(const m of hits)add(map,word,type,role,m[0],m.index,"media");}}
function mergeAliases(list){const removed=new Set();for(let i=0;i<list.length;i++){if(removed.has(i))continue;for(let j=0;j<list.length;j++){if(i===j||removed.has(j))continue;const a=list[i],b=list[j];if(a.type!==b.type)continue;const ka=canonicalKey(a.name),kb=canonicalKey(b.name);if(a.type==="PERSON"&&(ka.includes(kb)||kb.includes(ka))){const keep=a.name.length>=b.name.length?a:b,drop=keep===a?b:a,ki=keep===a?i:j,kd=keep===a?j:i;if(drop.name!==keep.name&&!keep.aliases.includes(drop.name))keep.aliases.push(drop.name);keep.mentions.push(...drop.mentions);removed.add(kd);if(kd===i)break;}}}return list.filter((_,i)=>!removed.has(i));}
function detect(raw){const map=new Map(),spans=[];detectInstitutional(raw,map,spans);detectLaws(raw,map,spans);detectPlaces(raw,map,spans);detectPersons(raw,map,spans);detectCollectives(raw,map);detectRoleEntities(raw,map);
 let out=mergeAliases([...map.values()]);out.forEach(e=>{e.aliases=[...new Set(e.aliases)];e.mentions=e.mentions.sort((a,b)=>a.index-b.index);});return out.sort((a,b)=>b.mentions.length-a.mentions.length||a.name.localeCompare(b.name,"es"));}
function mentionsIn(text,entities){const n=ns.Spanish.strip(text),out=[];for(const e of entities){const forms=[e.name,...e.aliases].filter(Boolean);if(forms.some(f=>n.includes(ns.Spanish.strip(f))))out.push(e.name);}return [...new Set(out)];}
ns.Entities={detect,mentionsIn,canonicalKey};
})(window);
