"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
function domainFrom(frames,entities,raw){const n=ns.Spanish.strip(raw),scores={investigacion:0,regulacion:0,narrativa:0,consumo:0},evidence={investigacion:[],regulacion:[],narrativa:[],consumo:[]};const add=(d,w,x)=>{scores[d]+=w;evidence[d].push(x);};
 if(/\b(fiscalia|fiscalía|ministerio publico|ministerio público|juez|tribunal|delito|homicidio|imputacion|imputación)\b/.test(n))add("investigacion",2,"léxico jurídico/investigativo");if(/\b(investigacion|investigación|indagatoria|esclarec|reconstruir los hechos|declaraciones)\b/.test(n))add("investigacion",1.5,"investigación/información");if(frames.some(f=>f.sense==="LEGAL_DETENTION"&&f.realization==="realized/asserted"))add("investigacion",1.5,"detención jurídica realizada");if(frames.some(f=>f.sense==="ATTRIBUTED_ALLEGATION"))add("investigacion",1,"alegación atribuida");
 if(/\b(restriccion|restricción|regulacion|regulación|limite|límite|tope|norma|prohibicion|prohibición)\b/.test(n))add("regulacion",2,"medida regulatoria");if(entities.some(e=>["GOVERNMENT","LAW"].includes(e.type)))add("regulacion",1,"autoridad/instrumento normativo");if(frames.some(f=>f.sense==="INSTITUTIONAL_IMPOSITION"))add("regulacion",1.5,"imposición institucional");if(/\b(impugn|amparo|exhort|negoci|rechaz.*medida|rechaz.*restric)\b/.test(n))add("regulacion",1,"respuesta/impugnación");
 if(/\b(cuento|bosque|bruja|hada|rey|reina|madrastra|hermanitos|vivieron felices|colorin colorado|colorín colorado)\b/.test(n))add("narrativa",2,"marcadores narrativos");if(/\b(abandon|captur|escap|retorn|regres.*casa|aventura|camino)\b/.test(n))add("narrativa",1,"arco de acción narrativa");if(frames.filter(f=>f.temporality==="pasado").length>=Math.max(3,frames.length*.35))add("narrativa",.75,"predominio narrativo pasado");
 if(/\b(compra|comprar|marca|consumidor|cliente|producto|precio|campana|campaña)\b/.test(n))add("consumo",2,"consumo/persuasión");if(/\b(adoptar|preferir|elegir|adquirir)\b/.test(n))add("consumo",1,"adopción");
 const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const [id,top]=ranked[0],second=ranked[1]?.[1]||0;if(top<2||top-second<.5)return {id:"generico",label:"genérico / dominio no determinado",score:top?Math.min(.55,top/6):.15,evidence:ranked.filter(x=>x[1]>0).map(([d,s])=>`${d}:${s}`)};const labels={investigacion:"investigación / esclarecimiento judicial",regulacion:"regulación / conflicto institucional",narrativa:"narrativa / transformación",consumo:"persuasión / consumo"};return {id,label:labels[id],score:Math.min(.95,.45+top*.09),evidence:evidence[id],alternatives:ranked.slice(1,3).map(([d,s])=>({id:d,score:s}))};}
function eventFamily(frame,domain){const n=ns.Spanish.strip(frame.evidence),s=frame.sense,p=frame.predicate;if(frame.type==="UNRESOLVED"||frame.relation_to_event==="unresolved")return "unresolved";if(frame.relation_to_event==="projection")return "projection";if(frame.relation_to_event==="retrospective")return "retrospective";if(frame.type==="SER"||frame.type==="ESTAR")return "attribute_state";
 if(s==="LEGAL_DETENTION")return "judicial_detention";if(s==="ATTRIBUTED_ALLEGATION")return "allegation";if(s==="INVESTIGATION_STATE")return "investigation_state";if(/\b(contradic|omitid|obstaculiz)\b/.test(n))return "information_obstruction_claim";if(/\b(esclarec|reconstru|informacion oficial|información oficial)\b/.test(n))return "information_request";
 if(s==="INSTITUTIONAL_IMPOSITION"||(/\b(restric|limite|límite|tope|medida|regul)\b/.test(n)&&/\b(impus|establec|reform|obliga|prohib|limita)\b/.test(n)))return "regulatory_restriction";if(frame.type==="DECIR"&&/\b(rechaz\w*|exhort\w*|pid\w*|solicit\w*|exig\w*|impugn\w*|ampar\w*|elimin\w*|negoci\w*)\b/.test(n))return "regulatory_challenge";if(/\b(impuesto sobre|por concepto del impuesto)\b/.test(n)&&/\b(gener|pag|cobr)\b/.test(n))return "economic_argument";if(frame.type==="DECIR"&&/\b(diagnost|sustento|justific|responsab|crisis)\b/.test(n))return "legitimacy_argument";
 if(/\babandon\w*\b|dej\w*\s+solos/.test(n))return "abandonment";if(/\b(guijarr\w*|piedrecit\w*|piedr\w*)\b/.test(n)&&/\b(camino|ruta|gui\w*|volver|regres\w*)\b/.test(n))return "orientation_success";if(/\b(miga\w*|desmig\w*)\b/.test(n))return /\b(no encontr\w*|pajar\w*.*com\w*|com\w*.*miga|fracaso|fall\w*)\b/.test(n)?"orientation_failure":"orientation_attempt";if(/\b(empuj\w*|precipit\w*|cerrojo|salvad\w*|liber\w*|escap\w*|abri[oó]\s+la\s+reja)\b/.test(n))return "counteraction";if(/\b(encerr\w*|reja|captur\w*|engord\w*|horno|asar\w*)\b/.test(n))return "capture";if(/\b(perla\w*|piedra preciosa|tesoro\w*)\b/.test(n)&&/\b(encontr\w*|tom\w*|llen\w*|vaci\w*)\b/.test(n))return "resource_acquisition";if(s==="MOTION_RETURN"||/\b(regres\w*|retorn\w*|lleg\w*.*casa|vivieron.*felices|acabaron las penas)\b/.test(n))return "return_restoration";
 if(frame.type==="DECIR")return frame.relation_to_event==="argument"?"argument":"communicative_operation";if(frame.type==="HACER")return "material_action";return frame.relation_to_event||"other";}
function signature(frame,family){const actor=frame.actor||"?",patient=frame.patient||"?",obj=frame.object||frame.predicate||"?";return `${family}|${actor}|${patient}|${obj}`;}
function groupEpisodes(frames,domain){const episodes=[];for(const f of frames){const family=eventFamily(f,domain);if(["unresolved"].includes(family))continue;const sig=signature(f,family);let e=[...episodes].reverse().find(x=>x.signature===sig&&f.sentenceIndex-x.last<=5);if(!e){e={id:`ep${episodes.length+1}`,signature:sig,family,frames:[],first:f.sentenceIndex,last:f.sentenceIndex};episodes.push(e);}e.frames.push(f);e.last=Math.max(e.last,f.sentenceIndex);}
 for(const e of episodes){e.evidence=e.frames.map(f=>f.evidence);e.evidenceCount=e.frames.length;e.confidence=e.frames.every(f=>f.confidence==="alta")?"alta":e.frames.length>=2?"media":"media-baja";e.realizationStatus=[...new Set(e.frames.map(f=>f.realization))];e.epistemicStatus=[...new Set(e.frames.map(f=>f.epistemic_status))];}return episodes;}
function episodeToOperation(ep,domain,entities){const f=ep.frames.find(x=>x.actor)||ep.frames[0],source=f.actor||"",actionTarget=f.patient||f.recipient||"",stateTarget=actionTarget;const communicative=f.type==="DECIR",actual=ep.frames.some(x=>x.realization==="realized/asserted"),epistemicallyDirect=ep.frames.some(x=>x.epistemic_status==="textual-assertion");const coreEligible=communicative&&actual&&epistemicallyDirect&&source&&actionTarget;const pendingMaterial=f.type==="HACER"&&actual;
 return {episodeId:ep.id,frameId:f.id,family:ep.family,source,actionTarget,target:stateTarget,stateTarget,type:ep.family,ontologicalType:f.type,D:null,phi:null,G:null,Ge:null,calculable:false,coreEligible,eligibility:coreEligible?"v0.40 communicative candidate":pendingMaterial?"material/institutional action — theoretical extension pending":"not eligible",confidence:ep.confidence,evidenceCount:ep.evidenceCount,evidence:{D:ep.evidence.slice(0,3).join(" / "),phi:"φ no se infiere por tipo de evento; requiere evidencia relacional source→target.",G:"G_e no se asigna automáticamente; requiere objetivo conductual del emisor y evidencia."},epistemicStatus:ep.epistemicStatus,realizationStatus:ep.realizationStatus};}
function build(raw,frames,entities){const domain=domainFrom(frames,entities,raw),episodes=groupEpisodes(frames,domain),operations=episodes.map(e=>episodeToOperation(e,domain,entities));return {domain,episodes,operations,calculableOperations:[],communicativeCandidates:operations.filter(o=>o.coreEligible),materialCandidates:operations.filter(o=>/material\/institutional/.test(o.eligibility))};}
ns.Events={domainFrom,eventFamily,groupEpisodes,episodeToOperation,build};
})(window);
