"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
function featureSet(analysis){const f=new Set(),frames=analysis.semantic.frames,raw=ns.Spanish.strip(analysis.raw),semi=analysis.semiotic||{},actors=[...new Set((semi.programs||[]).flatMap(p=>[p.actor]).filter(Boolean))];if(actors.length===2)f.add("two_players");if(actors.length>=3)f.add("three_or_more_players");if((semi.programs||[]).length>1){f.add("sequential");f.add("ordered_moves");}if((semi.counterPrograms||[]).length){f.add("conflict");f.add("distributional_conflict");}if((semi.counterPrograms||[]).length&&(semi.programs||[]).some(p=>p.families?.includes("regulatory_restriction"))){f.add("bargaining");f.add("institutional");f.add("negotiable_outcome");}const strategicRaw=raw.replace(/\bde acuerdo con\b/g," ");if(/\b(oferta|propuesta|contraoferta|ofrecio|ofreció|propuso)\b/.test(strategicRaw))f.add("offers");if(/\b(acuerdo|acordaron|acepto|aceptó)\b/.test(strategicRaw))f.add("agreement");if(/\b(amparo|litig|salir del mercado|alternativa|desacuerdo)\b/.test(raw))f.add("outside_option");if(/\b(punto de desacuerdo|disagreement)\b/.test(raw))f.add("disagreement_point");if(/\b(alternativamente|contraoferta|turnos de oferta|oferta.*respond)\b/.test(raw))f.add("alternating_offers");if(/\b(descuento|impaciencia|factor de descuento)\b/.test(raw))f.add("discounting");const questions=frames.filter(x=>x.type==="DECIR"&&/preguntar|pedir|solicitar|exigir/.test(x.predicate));if(questions.length&&analysis.events.episodes.some(e=>/allegation|information_obstruction/.test(e.family)))f.add("principal_queries");if(/\b(informacion privada|información privada|tipo privado|conoce.*pero.*desconoce|ocult[oa].*informacion)\b/.test(raw)){f.add("information_asymmetry");f.add("private_information");f.add("hidden_type");f.add("informed_actor");f.add("uninformed_actor");}if(/\b(señal|senal|mensaje|credencial|certifica)\b/.test(raw)){f.add("signaling");f.add("signal");}if(frames.some(x=>x.type==="DECIR"))f.add("communication");if((semi.subgames||[]).some(s=>s.family==="amenaza–respuesta")){f.add("threat");f.add("response");f.add("adaptation");f.add("conflict");}if((semi.programs||[]).some(p=>p.families?.includes("migration_coordination")))f.add("coordination");return f;}
function scoreGame(game,features){let matched=[],missing=[],excluded=[];for(const tag of game.tags)if(features.has(tag))matched.push(tag);for(const req of game.requires){if(features.has(req))matched.push(req);else missing.push(req);}for(const ex of game.excludes)if(features.has(ex))excluded.push(ex);const optionalHits=game.tags.filter(t=>features.has(t)).length,optionalRatio=game.tags.length?optionalHits/game.tags.length:0,reqRatio=game.requires.length?(game.requires.length-missing.length)/game.requires.length:1,score=Math.max(0,Math.min(1,.55*reqRatio+.45*optionalRatio-(excluded.length?.5:0))),eligible=missing.length===0&&excluded.length===0&&optionalHits===game.tags.length;return{gameId:game.id,label:game.label,family:game.family,score,matched:[...new Set(matched)],missing,excluded,eligible,tagRatio:optionalRatio,solution:game.solution};}
function subgamesFor(analysis){return (analysis.semiotic?.subgames||[]).map(s=>({...s,status:"estructura semiótica reconstruida; juego canónico sólo si requisitos específicos se cumplen"}));}
function scenariosFor(){return[{id:"OBS",label:"Estado observado",kind:"baseline",confidence:"observado",terminalG:{},description:"Marco descriptivo. No asigna Gτ numérico."}];}
function analyze(analysis){const features=featureSet(analysis),all=ns.GameOntology.catalog.map(g=>scoreGame(g,features)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score),candidates=all.slice(0,10),eligible=all.filter(x=>x.eligible&&x.score>=.72),integrity=analysis.semantic.integrity||{},globalGate=(integrity.unresolvedRatio??1)<=.25&&(integrity.resolvedActorRatio??0)>=.65&&(analysis.semiotic?.subgames?.length||0)<=1,determined=globalGate&&eligible.length&&(!eligible[1]||eligible[0].score-eligible[1].score>=.08)?eligible[0]:null;return{version:"game-engine-v0.54-mediated",features:[...features],catalogSize:ns.GameOntology.count,candidates,determined,globalGate,integrityGate:{unresolvedRatio:integrity.unresolvedRatio,resolvedActorRatio:integrity.resolvedActorRatio,subgames:analysis.semiotic?.subgames?.length||0},players:[],subgames:subgamesFor(analysis),scenarios:scenariosFor(analysis)};}
ns.Games={featureSet,scoreGame,analyze};
})(window);
