"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
function featureSet(analysis){const f=new Set(),frames=analysis.semantic.frames,eps=analysis.events.episodes,ops=analysis.events.operations,raw=ns.Spanish.strip(analysis.raw),semi=analysis.semiotic||{},strategicActors=[...new Set((semi.programs||[]).flatMap(p=>[p.actor,p.target]).filter(Boolean))],actors=strategicActors.length?strategicActors:[...new Set(frames.flatMap(x=>[x.actor,x.patient]).filter(Boolean))];
 if(actors.length===2)f.add("two_players");if(actors.length>=3)f.add("three_or_more_players");if((semi.programs||[]).length>1||frames.length>1){f.add("sequential");f.add("ordered_moves");}
 if((semi.counterPrograms||[]).length){f.add("conflict");f.add("distributional_conflict");}
 if((semi.counterPrograms||[]).length&&eps.some(e=>e.family==="regulatory_restriction")&&eps.some(e=>e.family==="regulatory_challenge")){f.add("bargaining");f.add("institutional");f.add("negotiable_outcome");}
 const strategicRaw=raw.replace(/\bde acuerdo con\b/g," ");if(/\b(oferta|propuesta|contraoferta|ofrecio|ofreció|propuso)\b/.test(strategicRaw))f.add("offers");if(/\b(acuerdo|acordaron|acepto|aceptó)\b/.test(strategicRaw))f.add("agreement");if(/\b(amparo|litig|salir del mercado|alternativa|desacuerdo)\b/.test(raw))f.add("outside_option");if(/\b(punto de desacuerdo|disagreement)\b/.test(raw))f.add("disagreement_point");if(/\b(alternativamente|contraoferta|turnos de oferta|oferta.*respond)\b/.test(raw))f.add("alternating_offers");if(/\b(descuento|impaciencia|factor de descuento)\b/.test(raw))f.add("discounting");
 const questions=frames.filter(x=>x.type==="DECIR"&&/preguntar|pedir|solicitar|exigir/.test(x.predicate));const allegations=eps.some(e=>/allegation|information_obstruction/.test(e.family));if(questions.length&&allegations){f.add("principal_queries");f.add("screening");}if(/\b(informacion privada|información privada|tipo privado|conoce.*pero.*desconoce|ocult[oa].*informacion)\b/.test(raw)){f.add("information_asymmetry");f.add("private_information");f.add("hidden_type");f.add("informed_actor");f.add("uninformed_actor");}
 if(/\b(señal|senal|mensaje|credencial|certifica)\b/.test(raw)){f.add("signaling");f.add("signal");}if(frames.some(x=>x.type==="DECIR"))f.add("communication");
 if(eps.some(e=>/abandonment|capture/.test(e.family))&&eps.some(e=>/counteraction|orientation|return/.test(e.family))){f.add("threat");f.add("response");f.add("adaptation");f.add("conflict");}
 if(/\b(cooper|coordina|acuerdo comun|acuerdo común)\b/.test(raw))f.add("coordination");if(/\b(amenaz|disuad|disuas)\b/.test(raw))f.add("deterrence");if(/\b(entrada|entrar al mercado|incumbente|competidor)\b/.test(raw))f.add("entry");if(/\bprecio\b/.test(raw))f.add("price");if(/\b(cantidad|produccion|producción)\b/.test(raw))f.add("quantity");if(/\b(vot|eleccion|elección|mayoria|mayoría)\b/.test(raw))f.add("voting");if(/\b(coalicion|coalición|alianza)\b/.test(raw))f.add("coalitions");if(/\b(repetid|cada vez|historial|reputacion|reputación)\b/.test(raw))f.add("repeated");if(/\b(subasta|puja|licitacion|licitación)\b/.test(raw))f.add("auction");if(/\b(delega|principal|agente|empleador|empleado)\b/.test(raw))f.add("principal_agent");
 return f;}
function scoreGame(game,features){let matched=[],missing=[],excluded=[];for(const tag of game.tags)if(features.has(tag))matched.push(tag);for(const req of game.requires){if(features.has(req))matched.push(req);else missing.push(req);}for(const ex of game.excludes)if(features.has(ex))excluded.push(ex);const optionalHits=game.tags.filter(t=>features.has(t)).length,optionalRatio=game.tags.length?optionalHits/game.tags.length:0;const reqRatio=game.requires.length?(game.requires.length-missing.length)/game.requires.length:1;const score=Math.max(0,Math.min(1,.55*reqRatio+.45*optionalRatio-(excluded.length?.5:0)));const eligible=missing.length===0&&excluded.length===0&&optionalHits===game.tags.length;return {gameId:game.id,label:game.label,family:game.family,score,matched:[...new Set(matched)],missing,excluded,eligible,tagRatio:optionalRatio,solution:game.solution};}
function playersFor(analysis){const ops=analysis.events.operations,out=[];function add(id,role,strategies=[]){if(!id||out.some(x=>x.id===id))return;out.push({id,role,observedStrategies:[...new Set(strategies.filter(Boolean))],preferenceStatus:"no inferida automáticamente",preferences:[]});}
 for(const o of ops){if(o.source)add(o.source,"actor/fuente observada",[o.type]);if(o.actionTarget)add(o.actionTarget,"destinatario/actor relacionado",[]);}return out.slice(0,10);}
function subgamesFor(analysis){const eps=analysis.events.episodes,out=[];const families=[...new Set(eps.map(e=>e.family))];if(families.includes("regulatory_restriction")&&families.includes("regulatory_challenge"))out.push({id:"SG1",label:"medida regulatoria ↔ respuesta",sequence:eps.filter(e=>/regulatory_restriction|regulatory_challenge|argument/.test(e.family)).map(e=>e.family),status:"estructura observada; solución estratégica no inferida"});if(families.some(x=>/abandonment|capture/.test(x))&&families.some(x=>/counteraction|orientation/.test(x)))out.push({id:"SG2",label:"amenaza ↔ respuesta",sequence:eps.filter(e=>/abandonment|capture|counteraction|orientation/.test(e.family)).map(e=>e.family),status:"secuencia observada"});if(families.includes("judicial_detention")||families.includes("information_request"))out.push({id:"SG3",label:"medida institucional / información",sequence:eps.filter(e=>/judicial|information|allegation/.test(e.family)).map(e=>e.family),status:"estructura informativa; juego no presumido"});return out;}
function scenariosFor(analysis){return [{id:"OBS",label:"Estado observado",kind:"baseline",confidence:"observado",terminalG:{},description:"Marco descriptivo del estado observado. La extrapolación cualitativa se produce después de la síntesis semiótica; este objeto no asigna Gτ numérico."}];}
function analyze(analysis){const features=featureSet(analysis),all=ns.GameOntology.catalog.map(g=>scoreGame(g,features)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score),candidates=all.slice(0,10);const eligible=all.filter(x=>x.eligible&&x.score>=.72);const determined=eligible.length&&(!eligible[1]||eligible[0].score-eligible[1].score>=.08)?eligible[0]:null;return {version:"game-engine-v0.53-mediated",features:[...features],catalogSize:ns.GameOntology.count,candidates,determined,players:playersFor(analysis),subgames:subgamesFor(analysis),scenarios:scenariosFor(analysis)};}
ns.Games={featureSet,scoreGame,analyze};
})(window);
