"use strict";
(function(global){
const ns=global.Limes52=global.Limes52||{};
function featureSet(analysis){const f=new Set(),domain=analysis.events.domain.id,frames=analysis.semantic.frames,episodes=analysis.events.episodes,raw=ns.Spanish.strip(analysis.raw);
 if(frames.length>1)f.add("ordered_moves");
 if(domain==="regulacion"){["bargaining","agreement","outside_option","negotiable_outcome","distributional_conflict","sequential","institutional","two_players"].forEach(x=>f.add(x));if(/mesa|negoci|revis/.test(raw))f.add("offers");if(/amparo|litig|impugn/.test(raw))f.add("outside_option");}
 if(domain==="narrativa"){["sequential","threat","response","adaptation","ordered_moves","two_players","conflict"].forEach(x=>f.add(x));}
 if(domain==="investigacion"){["information_asymmetry","screening","principal_queries","sequential","ordered_moves","informed_actor","uninformed_actor","monitoring","inspection"].forEach(x=>f.add(x));if(/contradic|omitid|falsedad|encubrimiento/.test(raw))f.add("hidden_information");if(/detenci|aprehension|aprehensión/.test(raw))f.add("enforcement");if(/declaracion|declaraciones|informacion|información/.test(raw))f.add("communication");if(/probable|habria|habría|hipotesis|hipótesis/.test(raw))f.add("incomplete_information");}
 if(/cooper|coordina|acuerdo/.test(raw))f.add("coordination");if(/amenaz|disuad|deterr/.test(raw))f.add("deterrence");if(/señal|senal|mensaje|declara/.test(raw))f.add("signaling");if(/ocult|informacion privada|información privada|tipo privado/.test(raw)){f.add("private_information");f.add("hidden_type");}
 if(/entrada|entrar al mercado|incumbente|competidor/.test(raw))f.add("entry");if(/precio/.test(raw))f.add("price");if(/cantidad|produccion|producción/.test(raw))f.add("quantity");if(/vot|eleccion|elección|mayoria|mayoría/.test(raw))f.add("voting");if(/coalicion|coalición|alianza/.test(raw))f.add("coalitions");if(/repetid|cada vez|historial|reputacion|reputación/.test(raw))f.add("repeated");if(/subasta|puja|licitacion|licitación/.test(raw))f.add("auction");
 return f;}
function scoreGame(game,features){let score=0,matched=[],missing=[];for(const tag of game.tags){if(features.has(tag)){score+=1;matched.push(tag);}}for(const req of game.requires){if(features.has(req)){score+=1.35;matched.push(req);}else missing.push(req);}for(const ex of game.excludes){if(features.has(ex))score-=2;}const denom=Math.max(2,game.tags.length+game.requires.length*1.35);return {gameId:game.id,label:game.label,family:game.family,score:Math.max(0,Math.min(1,score/denom)),matched:[...new Set(matched)],missing,solution:game.solution};}
function domainBoost(candidate,domain){const id=candidate.gameId;if(domain==="investigacion"&&["screening","inspection","signaling","cheap_talk","bayesian","principal_agent","adverse_selection"].includes(id))candidate.score=Math.min(1,candidate.score+.20);if(domain==="regulacion"&&["nash_bargaining","alternating_offers","rubinstein","bargaining_information","veto_player"].includes(id))candidate.score=Math.min(1,candidate.score+.22);if(domain==="narrativa"&&["sequential_threat_response","deterrence","centipede","commitment"].includes(id))candidate.score=Math.min(1,candidate.score+.25);return candidate;}
function playersFor(analysis){const d=analysis.events.domain.id,E=analysis.entities,ops=analysis.events.operations,players=[];function add(id,role,observed=[],status="observado/inferido"){if(id&&!players.some(p=>p.id===id))players.push({id,role,observedStrategies:[...new Set(observed)],preferenceStatus:status,preferences:[]});}
 if(d==="investigacion"){
  const fgr=E.find(e=>/Fiscalía General de la República/.test(e.name))?.name||"Fiscalía General de la República",corr=E.find(e=>/Corrales/.test(e.name))?.name||"actor investigado/testigo";add(fgr,"autoridad investigadora",["investigar","contrastar declaraciones","obtener información","ejecutar/solicitar medidas institucionales"]);add(corr,"investigado / fuente potencial de información",["declarar","aportar/retener información"],"conducta atribuida parcialmente; preferencias no observadas");const judge=E.find(e=>e.type==="COURT_ROLE");if(judge)add(judge.name,"autorizador institucional",["autorizar/denegar medida"],"rol institucional; no jugador principal salvo decisión controvertida");
 }
 if(d==="regulacion"){add("gobierno / autoridades","autoridad reguladora",["mantener","modificar","retirar"]);add("Comunidad de Pequeños Anfitriones","actor regulado / impugnante",["aceptar","negociar","impugnar/litigar","presionar","salir"]);}
 if(d==="narrativa"){add("Hänsel y Gretel","actor vulnerable / resistencia",["orientarse","resistir","contraactuar","escapar","retornar"]);if(E.some(e=>e.name==="madrastra"))add("madrastra","oponente inicial",["abandonar"]);if(E.some(e=>e.name==="bruja"))add("bruja","oponente posterior",["capturar","amenazar"]);}
 if(!players.length){const ids=[...new Set(ops.flatMap(o=>[o.source,o.actionTarget]).filter(Boolean))].slice(0,6);ids.forEach(id=>add(id,"actor estratégico potencial",ops.filter(o=>o.source===id).map(o=>o.type),"inferido"));}
 return players;}
function subgamesFor(analysis){const d=analysis.events.domain.id,ops=analysis.events.operations,out=[];
 if(d==="investigacion"){
  const det=ops.filter(o=>o.family==="judicial_detention"||o.family==="judicial_authorization");const info=analysis.semantic.frames.filter(f=>/ATTRIBUTED_ALLEGATION|INVESTIGATION_OPEN|KNOWLEDGE_GOAL/.test(f.sense)||/contradic|omitid|informacion|información/.test(ns.Spanish.strip(f.evidence)));
  if(det.length)out.push({id:"SG1",label:"medida judicial / acceso al investigado",sequence:det.map(o=>o.type),status:"hechos institucionales observados"});if(info.length)out.push({id:"SG2",label:"información / verificación / posible screening",sequence:info.slice(0,8).map(f=>`${f.type}:${f.sense||f.predicate}`),status:"estructura informativa; preferencias del investigado no establecidas"});
 }
 if(d==="regulacion"){const a=ops.filter(o=>o.family==="regulatory_restriction"),b=ops.filter(o=>/challenge|argument/.test(o.family));if(a.length)out.push({id:"SG1",label:"imposición/implementación regulatoria",sequence:a.map(o=>o.type),status:"observado"});if(b.length)out.push({id:"SG2",label:"impugnación / respuesta institucional",sequence:b.map(o=>o.type),status:"respuesta del actor regulado observada; reacción de autoridad puede faltar"});}
 if(d==="narrativa"){const a=ops.filter(o=>/abandon|orientation/.test(o.family)),b=ops.filter(o=>/capture|counteraction/.test(o.family)),c=ops.filter(o=>/resource|return/.test(o.family));if(a.length)out.push({id:"SG1",label:"abandono ↔ orientación",sequence:a.map(o=>o.type),status:"observado"});if(b.length)out.push({id:"SG2",label:"captura ↔ contraacción",sequence:b.map(o=>o.type),status:"observado"});if(c.length)out.push({id:"SG3",label:"restauración",sequence:c.map(o=>o.type),status:"transformación; no necesariamente juego"});}
 return out;}
function scenariosFor(analysis,candidates){const d=analysis.events.domain.id,out=[];
 if(d==="regulacion"){out.push({id:"REG-BASE",label:"Baseline: restricción vigente",kind:"baseline",confidence:"observado",terminalG:{impacto_regulatorio:.35,impugnacion:.55},description:"La restricción permanece vigente; la impugnación continúa sin respuesta institucional conclusiva."},{id:"REG-NEG",label:"Negociación / modificación",kind:"strategic",confidence:"plausible-no-resuelto",terminalG:{impacto_regulatorio:.60,impugnacion:.68},description:"Se abre negociación y la restricción se modifica parcialmente."},{id:"REG-RET",label:"Retiro / eliminación",kind:"strategic",confidence:"hipotético",terminalG:{impacto_regulatorio:.88,impugnacion:.85},description:"La restricción se retira o reduce sustancialmente."});}
 else if(d==="investigacion"){out.push({id:"INV-BASE",label:"Baseline: investigación abierta",kind:"baseline",confidence:"observado",terminalG:{investigacion:.40},description:"La investigación sigue abierta; la detención es un hecho, pero su aporte informativo aún no está realizado."},{id:"INV-INFO",label:"Detención produce información verificable",kind:"strategic",confidence:"proyección textual",terminalG:{investigacion:.72},description:"La medida facilita información nueva y verificable que incrementa capacidad de esclarecimiento."},{id:"INV-NOINFO",label:"Detención no modifica el contenido informativo",kind:"strategic",confidence:"contrafactual plausible",terminalG:{investigacion:.42},description:"La detención no produce información adicional suficiente para cambiar sustancialmente el esclarecimiento."});}
 else if(d==="narrativa"){out.push({id:"NAR-OBS",label:"Arco observado",kind:"observed",confidence:"derivado del texto",terminalG:{supervivencia:1},description:"Estado terminal observado de supervivencia/retorno; no sobrescribe G_e locales."});}
 else out.push({id:"GEN-OBS",label:"Escenario observado",kind:"baseline",confidence:"preliminar",terminalG:{generico:.5},description:"Escenario preliminar; requiere definición manual."});return out;}
function analyze(analysis){const features=featureSet(analysis),domain=analysis.events.domain.id,candidates=ns.GameOntology.catalog.map(g=>domainBoost(scoreGame(g,features),domain)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,8);const determined=candidates[0]&&candidates[0].score>=.72&&candidates[0].missing.length<=1?candidates[0]:null;return {version:"game-engine-v0.52",features:[...features],catalogSize:ns.GameOntology.count,candidates,determined,players:playersFor(analysis),subgames:subgamesFor(analysis),scenarios:scenariosFor(analysis,candidates)};}
ns.Games={featureSet,scoreGame,analyze};
})(window);
