"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
assert.strictEqual(scripts.length,1);
function fakeEl(){return {value:"",innerHTML:"",className:"",dataset:{},addEventListener(){},querySelector(){return fakeEl();},querySelectorAll(){return []},insertAdjacentHTML(){},closest(){return fakeEl();}};}
const sandbox={window:{},console,Number,Math,String,JSON,Map,Set,RegExp,Error,document:{querySelector(){return fakeEl();},querySelectorAll(){return []},createElement(){return {click(){}}}},Blob:function(){},URL:{createObjectURL(){return ""},revokeObjectURL(){}},alert(){}};
sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(scripts[0],sandbox);
const core=sandbox.LimesCore;
function analysisFor(raw){
 const code=`(function(){const raw=${JSON.stringify(raw)};const sents=splitSentences(raw),tok=tokens(raw),freq={};tok.forEach(w=>freq[w]=(freq[w]||0)+1);const concepts=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,10);const actors=detectActors(raw);const evidence={S:sents.filter(s=>score(lex.ser,s)).slice(0,4),E:sents.filter(s=>score(lex.estar,s)||score(lex.barrier,s)).slice(0,4),D:sents.filter(s=>score(lex.decir,s)||score(lex.operation,s)).slice(0,4),H:sents.filter(s=>score(lex.hacer,s)).slice(0,4),phi:sents.filter(s=>score(lex.barrier,s)||/duda|precio|acceso|barrera|resistencia/i.test(s)).slice(0,4),G:sents.filter(s=>/busca|intenta|pretende|transformar|llevar|convertir/i.test(s)).slice(0,4)};const a={actors,concepts,evidence,scores:{S:score(lex.ser,raw),E:score(lex.estar,raw),D:score(lex.decir,raw)+score(lex.operation,raw),H:score(lex.hacer,raw),barrier:score(lex.barrier,raw),positive:score(lex.positive,raw)},raw};const sc=inferScenario(a);return {profile:a.profile,profileScore:a.profileScore,actors:a.actors,events:a.events,scenario:sc};})()`;
 return vm.runInContext(code,sandbox);
}
const tests=[];function test(n,fn){tests.push({n,fn});}
test("núcleo conserva ecuación",()=>{const A={id:"A",S:.8,E:.7,H:.25},B={id:"B",S:.55,E:.6,H:.2};const r=core.predictInteraction(A,B,{source:"A",target:"B",D:.7,phi:.5,G:.8});assert(Math.abs(r.X-.196)<1e-12);assert(Math.abs(r.deltaH-.1176)<1e-12);});
test("noticia regulatoria usa modo mixto y no electoral",()=>{const raw="La Comunidad de Pequeños Anfitriones rechazó el límite impuesto por las autoridades capitalinas de sólo poder ofrecer hospedaje eventual durante el 50 por ciento de las noches del año. En conferencia de prensa aseguraron que no existen justificaciones y exhortaron al Gobierno a eliminar la medida.";const out=analysisFor(raw);assert.strictEqual(out.profile.id,"regulacion");assert.strictEqual(out.scenario.issueMode,"mixto");assert(!out.scenario.hLabel.toLowerCase().includes("votar"));});
test("noticia genera eventos regulatorios bidireccionales",()=>{const raw="La Comunidad de Pequeños Anfitriones rechazó el límite impuesto por las autoridades capitalinas de sólo poder ofrecer hospedaje eventual durante el 50 por ciento de las noches del año. En conferencia de prensa aseguraron que no existen justificaciones y exhortaron al Gobierno a eliminar la medida.";const out=analysisFor(raw);assert(out.events.some(e=>e.source==="gobierno / autoridades"&&e.target==="Comunidad de Pequeños Anfitriones"&&e.type==="regulación coercitiva"&&e.G<=.2));assert(out.events.some(e=>e.source==="Comunidad de Pequeños Anfitriones"&&e.target==="Comunidad de Pequeños Anfitriones"&&e.type==="impugnación / demanda"&&e.G>=.75));});
test("falsos actores periodísticos y narrativos se eliminan",()=>{const actors=vm.runInContext(`detectActors("Indicaron que el gobierno respondió. Aseguraron que la comunidad resistirá. Lamentaron la medida. Dinero publicó. Así habló Gretel. Basta dijo Hänsel. Brillaba la luna.")`,sandbox).map(a=>a.name.toLowerCase());for(const bad of ["indicaron","aseguraron","lamentaron","dinero","así","basta","brillaba"])assert(!actors.includes(bad));assert(actors.some(a=>a.includes("gretel"))||actors.some(a=>a.includes("hänsel")));});
test("cuento genera seis fases y resolución",()=>{const raw="Mañana la madrastra llevará a los niños al bosque para abandonarlos. Brillaba la luna y Hänsel dejó guijarros para encontrar el camino de vuelta. Camino del bosque, Hänsel iba desmigajando el pan y dejaba caer miguitas. Los pájaros se comieron las migas. La bruja agarró a Hänsel y lo encerró detrás de una reja. Gretel empujó a la bruja al horno y los niños escaparon. Volvieron a casa con perlas y piedras preciosas y vivieron felices.";const out=analysisFor(raw);const phases=out.events.map(e=>e.phase);for(const p of ["Fase 1","Fase 2","Fase 3","Fase 4","Fase 5","Fase 6"])assert(phases.some(x=>x.includes(p)));assert(out.events.some(e=>e.type==="orientación fallida"&&e.G<=.35&&e.phi<=.12));assert(out.events.some(e=>e.type==="retorno / agencia restaurada"&&e.G===1));});
test("negación de abandono no genera coerción",()=>{const op=vm.runInContext(`operationFromSentence("Dios no nos abandonará y se acostó de nuevo.", CORPUS_PROFILES.find(p=>p.id==="narrativa"))`,sandbox);assert.strictEqual(op,null);});
test("curva narrativa con desenlace termina alta",()=>{const raw="Mañana la madrastra llevará a los niños al bosque para abandonarlos. Brillaba la luna y Hänsel dejó guijarros para encontrar el camino de vuelta. Camino del bosque, Hänsel iba desmigajando el pan y dejaba caer miguitas. Los pájaros se comieron las migas. La bruja agarró a Hänsel y lo encerró detrás de una reja. Gretel empujó a la bruja al horno y los niños escaparon. Volvieron a casa con perlas y piedras preciosas y vivieron felices.";const out=analysisFor(raw);const actors=["Hänsel y Gretel","madrastra / mujer del padre","Hänsel","Gretel","bruja"].map(id=>({id,S:.85,E:.80,H:id==="Hänsel y Gretel"?.25:.25,hmode:id==="Hänsel y Gretel"?"sí":"no"}));const res=core.runSequence(actors,out.events);const kids=res.actors.find(a=>a.id==="Hänsel y Gretel");assert(kids.H>.70);});
test("incluye UI de modo de issue y agrupación",()=>{assert(html.includes('id="issueMode"'));assert(html.includes('id="eventGrouping"'));assert(html.includes('functionalRole'));});
test("sin utilidad esperada",()=>{const lower=html.toLowerCase();assert(!lower.includes("expectedutility")&&!lower.includes("utility("));});
let p=0;for(const t of tests){try{t.fn();console.log("PASS",t.n);p++;}catch(e){console.error("FAIL",t.n,"\n ",e.message);}}console.log(`\n${p}/${tests.length} PASS`);if(p!==tests.length)process.exit(1);
