(() => {
"use strict";
const $=s=>document.querySelector(s), esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const clean=v=>v.trim().replace(/^\/+|\/+$/g,"").replace(/\/+/g,"/"), slugify=v=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
const form=$("#content-form"),homeForm=$("#home-form"),tree=$("#site-tree"),loadStatus=$("#load-status"),formStatus=$("#form-status"),homeStatus=$("#home-status"),editor=$("#body-editor");
const type=$("#content-type"),title=$("#title"),slug=$("#slug"),description=$("#description"),parent=$("#parent-menu"),folder=$("#folder"),date=$("#date-published"),addMenu=$("#add-menu"),addIndex=$("#add-index");
const preview=$("#preview-panel"),frame=$("#preview-frame");
let navigation=[],mode="existing",loadedPath=null,loadedOriginalTitle=null,loadedParentPath=null,homeDocument=null,imageCounter=0;

function flatten(items,prefix=[]){const out=[];for(const item of items){const path=[...prefix,item.label];out.push({item,path,label:path.join(" › ")});if(item.children)out.push(...flatten(item.children,path))}return out}
function findNode(items,labels){let list=items,current=null;for(const label of labels){current=list.find(x=>x.label===label);if(!current)return null;list=current.children||[]}return current}
function findItemByUrl(items,url){for(const item of items){if(item.url===url)return item;if(item.children){const found=findItemByUrl(item.children,url);if(found)return found}}return null}
function findParentOfUrl(items,url,path=[]){for(const item of items){if(item.children){if(item.children.some(x=>x.url===url))return [...path,item.label];const nested=findParentOfUrl(item.children,url,[...path,item.label]);if(nested)return nested}}return null}
function renderParents(){parent.innerHTML="";for(const opt of flatten(navigation)){const el=document.createElement("option");el.value=JSON.stringify(opt.path);el.textContent=opt.label;parent.appendChild(el)}}
function renderTree(){tree.innerHTML="";const home=document.createElement("button");home.type="button";home.className="tree-item tree-home";home.dataset.path="index.html";home.textContent="⌂ Portada";tree.append(home);const list=document.createElement("ul");list.className="tree-root";list.append(...navigation.filter(x=>x.url!=="index.html").map(node=>treeNode(node)));tree.append(list)}
function treeNode(node){const li=document.createElement("li"),row=document.createElement(node.url?"button":"span");row.className="tree-item";if(node.url){row.type="button";row.dataset.path=node.url}row.textContent=node.label;li.append(row);if(node.children?.length){const ul=document.createElement("ul");ul.append(...node.children.map(treeNode));li.append(ul)}return li}
function showOnly(which){form.hidden=which!=="page";homeForm.hidden=which!=="home"}
function setActive(path){document.querySelectorAll(".tree-item.active").forEach(x=>x.classList.remove("active"));document.querySelector(`.tree-item[data-path="${CSS.escape(path)}"]`)?.classList.add("active")}
function updateType(){const value=type.value;$("#date-field").hidden=value!=="blog";$("#folder-field").hidden=value==="page";if(value==="blog"){folder.value="blog";const blog=flatten(navigation).find(x=>x.item.label==="Blog");if(blog)parent.value=JSON.stringify(blog.path)}else if(value==="page")folder.value=""}
function sanitizeHTML(raw){const doc=new DOMParser().parseFromString(`<div>${raw}</div>`,"text/html"),root=doc.body.firstElementChild,allowed=new Set(["P","BR","H2","H3","STRONG","EM","A","UL","OL","LI","BLOCKQUOTE","FIGURE","IMG","FIGCAPTION","SPAN"]);[...root.querySelectorAll("*")].forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return} [...el.attributes].forEach(a=>{const ok=(el.tagName==="A"&&["href","target","rel"].includes(a.name))||(el.tagName==="IMG"&&["src","alt","loading","width","height"].includes(a.name))||(el.tagName==="SPAN"&&a.name==="class"&&a.value==="small-caps");if(!ok)el.removeAttribute(a.name)});if(el.tagName==="A"){el.setAttribute("rel","noopener");if(/^https?:/i.test(el.getAttribute("href")||""))el.setAttribute("target","_blank")}if(el.tagName==="IMG")el.setAttribute("loading","lazy")});return root.innerHTML.trim()}
function buildData(){const contentType=type.value,s=clean(slug.value),f=clean(folder.value),path=contentType==="page"?`${s}.html`:contentType==="blog"?`blog/${s}.html`:`${f}/${s}.html`,parentPath=JSON.parse(parent.value);return{type:contentType,title:title.value.trim(),slug:s,description:description.value.trim(),body:sanitizeHTML(editor.innerHTML),date:date.value,path,parentPath,kicker:contentType==="blog"?"Blog":parentPath.at(-1)}}
function validate(d){if(!d.title)throw new Error("El título es obligatorio.");if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.slug))throw new Error("El slug sólo admite minúsculas, números y guiones.");if(d.description.length<40)throw new Error("La descripción SEO necesita al menos 40 caracteres.");if(!d.body)throw new Error("El contenido no puede quedar vacío.");if(d.type==="subpage"&&!clean(folder.value))throw new Error("Indica la carpeta de destino.");if(mode==="existing"&&d.path!==loadedPath)throw new Error("La ruta de una página publicada permanece bloqueada.")}
const rootFor=path=>"../".repeat(path.split("/").length-1),canonical=path=>`https://www.gutierrezvidal.com/${path}`;
function pageHTML(d){const root=rootFor(d.path),url=canonical(d.path),schema={"@context":"https://schema.org","@type":d.type==="blog"?"BlogPosting":"WebPage",headline:d.title,description:d.description,url,inLanguage:"es-MX",author:{"@type":"Person",name:"Carlos Adolfo Gutiérrez Vidal"}};if(d.type==="blog"&&d.date)schema.datePublished=d.date;const kicker=d.type==="blog"&&d.date?d.date:d.kicker;return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="author" content="Carlos Adolfo Gutiérrez Vidal"><meta name="description" content="${esc(d.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${url}"><link rel="icon" href="${root}public/assets/favicon.ico" sizes="any"><meta property="og:type" content="${d.type==="blog"?"article":"website"}"><meta property="og:title" content="${esc(d.title)}"><meta property="og:description" content="${esc(d.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://www.gutierrezvidal.com/public/assets/og-home.jpg"><script type="application/ld+json">${JSON.stringify(schema)}</script><title>${esc(d.title)} · Carlos Adolfo Gutiérrez Vidal</title><link rel="stylesheet" href="${root}src/css/site-v2.2.css"></head><body data-root="${root}"><div data-site-header></div><main class="page"><header class="page-header"><p class="page-kicker">${esc(kicker)}</p><h1 class="page-title">${esc(d.title)}</h1><p class="page-deck">${esc(d.description)}</p></header><article class="prose">${d.body}</article></main><div data-site-footer></div><script src="${root}src/js/site-shell-v2.1.js"></script></body></html>`}
function inferType(path){return path.startsWith("blog/")?"blog":path.includes("/")?"subpage":"page"}
function inferFolder(path){const p=path.split("/");return p.length>1?p.slice(0,-1).join("/"):""}
function extractDescription(doc){return doc.querySelector('meta[name="description"]')?.content?.trim()||doc.querySelector(".page-deck")?.textContent?.trim()||""}
function extractDate(doc){for(const n of doc.querySelectorAll('script[type="application/ld+json"]')){try{const x=JSON.parse(n.textContent);if(x.datePublished)return x.datePublished}catch{}}return""}
async function loadPage(path){setActive(path);loadStatus.textContent=`Cargando ${path}…`;if(path==="index.html")return loadHome();try{const html=await GVPatches.getFile(path),doc=new DOMParser().parseFromString(html,"text/html"),article=doc.querySelector("article.prose"),pageTitle=doc.querySelector(".page-title")?.textContent?.trim();if(!article||!pageTitle)throw new Error("La página no usa la estructura editable esperada.");mode="existing";loadedPath=path;loadedOriginalTitle=pageTitle;loadedParentPath=findParentOfUrl(navigation,path);type.value=inferType(path);updateType();title.value=pageTitle;slug.value=path.split("/").at(-1).replace(/\.html$/,"");description.value=extractDescription(doc);editor.innerHTML=article.innerHTML;folder.value=inferFolder(path);date.value=extractDate(doc);if(loadedParentPath)parent.value=JSON.stringify(loadedParentPath);type.disabled=slug.disabled=folder.disabled=true;addMenu.checked=addIndex.checked=false;$("#navigation-options").hidden=true;$("#editor-mode-label").textContent="Página publicada";$("#editor-heading").textContent=pageTitle;$("#path-badge").textContent=path;showOnly("page");loadStatus.textContent=`Página cargada: ${path}`;formStatus.textContent=""}catch(e){loadStatus.textContent=e.message}}
async function loadHome(){try{const html=await GVPatches.getFile("index.html");homeDocument=new DOMParser().parseFromString(html,"text/html");$("#home-title").value=homeDocument.title;$("#home-description").value=homeDocument.querySelector('meta[name="description"]')?.content||"";$("#home-label").value=homeDocument.querySelector(".practice-statement__label")?.textContent.trim()||"";$("#home-headline").value=homeDocument.querySelector("#practice-title")?.textContent.trim()||"";$("#home-intro").value=homeDocument.querySelector(".practice-statement__intro > p:last-child")?.textContent.trim()||"";const axes=[...homeDocument.querySelectorAll(".practice-statement__axes article")];$("#home-axes").innerHTML=axes.map((a,i)=>`<fieldset><legend>Eje ${i+1}</legend><label><span>Título</span><input data-axis-title value="${esc(a.querySelector("h2")?.textContent.trim()||"")}"></label><label><span>Texto</span><textarea data-axis-text rows="3">${esc(a.querySelector("p:last-child")?.textContent.trim()||"")}</textarea></label></fieldset>`).join("");showOnly("home");loadStatus.textContent="Portada cargada. El panorama, hotspots y scripts permanecerán intactos."}catch(e){loadStatus.textContent=e.message}}
function newPage(){mode="new";loadedPath=null;form.reset();editor.innerHTML="<p></p>";type.disabled=slug.disabled=folder.disabled=false;type.value="page";updateType();addMenu.checked=addIndex.checked=true;$("#navigation-options").hidden=false;$("#editor-mode-label").textContent="Página nueva";$("#editor-heading").textContent="Crear contenido";$("#path-badge").textContent="Sin guardar";showOnly("page");loadStatus.textContent="Nueva página preparada."}
function addToMenu(d){const node=findNode(navigation,d.parentPath);if(!node)throw new Error("No se encontró el menú padre.");node.children=node.children||[];if(node.children.some(x=>x.url===d.path))throw new Error("La ruta ya existe en el menú.");node.children.push({label:d.title,url:d.path})}
async function pathAlreadyExists(path){const patches=await GVPatches.listPatches();if(Object.hasOwn(patches,path))return true;try{await GVPatches.getFile(path);return true}catch{return false}}
async function updatedSitemap(d){const xml=await GVPatches.getFile("sitemap.xml"),url=canonical(d.path);if(xml.includes(`<loc>${url}</loc>`))return xml;return xml.replace("</urlset>",`  <url><loc>${url}</loc><changefreq>monthly</changefreq><priority>0.6</priority></url>\n</urlset>`)}
async function insertImage(file){if(!file)return;const base=slugify(file.name.replace(/\.[^.]+$/, ""))||`imagen-${++imageCounter}`,ext=(file.name.match(/\.[a-z0-9]+$/i)||[".jpg"])[0].toLowerCase(),name=`${base}-${Date.now()}${ext}`,path=`public/images/${name}`,alt=window.prompt("Texto alternativo de la imagen:",base.replaceAll("-"," "));if(alt===null)return;const caption=window.prompt("Pie de foto (opcional):","")||"";await GVPatches.savePatch(path,file);const figure=document.createElement("figure");figure.innerHTML=`<img src="/${path}" alt="${esc(alt)}" loading="lazy">${caption?`<figcaption>${esc(caption)}</figcaption>`:""}`;const sel=getSelection();if(sel.rangeCount){const range=sel.getRangeAt(0);range.deleteContents();range.insertNode(figure);range.setStartAfter(figure);range.collapse(true);sel.removeAllRanges();sel.addRange(range)}else editor.append(figure);formStatus.textContent=`Imagen añadida: ${path}`}
function command(button){const cmd=button.dataset.command,value=button.dataset.value||null;editor.focus();if(cmd==="smallcaps"){document.execCommand("styleWithCSS",false,false);document.execCommand("insertHTML",false,`<span class="small-caps">${esc(getSelection().toString()||"versalitas")}</span>`)}else if(cmd==="link"){const href=window.prompt("URL del enlace:","https://");if(href)document.execCommand("createLink",false,href)}else document.execCommand(cmd,false,value)}
function updateHomeDocument(){const doc=homeDocument;doc.title=$("#home-title").value.trim();const desc=$("#home-description").value.trim();doc.querySelector('meta[name="description"]')?.setAttribute("content",desc);doc.querySelector('meta[property="og:description"]')?.setAttribute("content",desc);doc.querySelector('meta[name="twitter:description"]')?.setAttribute("content",desc);doc.querySelector(".practice-statement__label").textContent=$("#home-label").value.trim();doc.querySelector("#practice-title").textContent=$("#home-headline").value.trim();doc.querySelector(".practice-statement__intro > p:last-child").textContent=$("#home-intro").value.trim();const fields=[...$("#home-axes").querySelectorAll("fieldset")],axes=[...doc.querySelectorAll(".practice-statement__axes article")];fields.forEach((f,i)=>{axes[i].querySelector("h2").textContent=f.querySelector("[data-axis-title]").value.trim();axes[i].querySelector("p:last-child").textContent=f.querySelector("[data-axis-text]").value.trim()});return "<!doctype html>\n"+doc.documentElement.outerHTML}
function showPreview(html){frame.src=URL.createObjectURL(new Blob([html],{type:"text/html"}));preview.hidden=false}

tree.addEventListener("click",e=>{const b=e.target.closest("[data-path]");if(b)loadPage(b.dataset.path)});$("#new-page").addEventListener("click",newPage);type.addEventListener("change",updateType);title.addEventListener("input",()=>{if(mode==="new")slug.value=slugify(title.value)});slug.addEventListener("input",()=>slug.value=slugify(slug.value));document.querySelectorAll(".rich-toolbar [data-command]").forEach(b=>b.addEventListener("click",()=>command(b)));$("#insert-image").addEventListener("click",()=>$("#image-file").click());$("#image-file").addEventListener("change",e=>insertImage(e.target.files[0]));
$("#preview-button").addEventListener("click",()=>{try{const d=buildData();validate(d);showPreview(pageHTML(d))}catch(e){formStatus.textContent=e.message}});$("#home-preview").addEventListener("click",()=>showPreview(updateHomeDocument()));$("#close-preview").addEventListener("click",()=>{preview.hidden=true;frame.src="about:blank"});
form.addEventListener("submit",async e=>{e.preventDefault();try{const d=buildData();validate(d);if(mode==="new"){if(await pathAlreadyExists(d.path))throw new Error(`La ruta ${d.path} ya existe.`);await GVPatches.savePatch(d.path,pageHTML(d));if(addMenu.checked){addToMenu(d);await GVPatches.savePatch("src/data/navigation.json",JSON.stringify(navigation,null,2)+"\n");renderTree()}await GVPatches.savePatch("sitemap.xml",await updatedSitemap(d));formStatus.textContent=`Página nueva guardada: ${d.path}`}else{await GVPatches.savePatch(loadedPath,pageHTML(d));if(d.title!==loadedOriginalTitle){const item=findItemByUrl(navigation,loadedPath);if(item)item.label=d.title;await GVPatches.savePatch("src/data/navigation.json",JSON.stringify(navigation,null,2)+"\n");loadedOriginalTitle=d.title;renderTree()}formStatus.textContent=`Página actualizada: ${loadedPath}`}}catch(err){formStatus.textContent=err.message}});
homeForm.addEventListener("submit",async e=>{e.preventDefault();try{const html=updateHomeDocument();await GVPatches.savePatch("index.html",html);homeStatus.textContent="Portada guardada en la actualización. El visor panorámico y sus scripts no fueron reemplazados."}catch(err){homeStatus.textContent=err.message}});
(async()=>{navigation=JSON.parse(await GVPatches.getFile("src/data/navigation.json"));renderParents();renderTree();updateType()})().catch(e=>loadStatus.textContent=e.message);
})();
