(() => {
  "use strict";
  const DB_NAME="gutierrezvidal-editor-patches", DB_VERSION=2, STORE="patches";
  function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function getValue(key){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).get(key);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()})}
  async function setValue(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
  async function clearAll(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).clear();tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
  const listPatches=async()=>await getValue("files")||{};
  async function savePatch(path,content){const files=await listPatches();files[path.replace(/^\/+/,"")]=content;await setValue("files",files);await setValue("updatedAt",new Date().toISOString());return files}
  async function removePatch(path){const files=await listPatches();delete files[path.replace(/^\/+/,"")];await setValue("files",files);return files}
  async function getFile(path){const clean=path.replace(/^\/+/,""),patches=await listPatches();if(Object.prototype.hasOwnProperty.call(patches,clean)){const value=patches[clean];if(value instanceof Blob)return await value.text();return String(value)}const response=await fetch(`../${clean}?editor-cache=${Date.now()}`,{cache:"no-store"});if(!response.ok)throw new Error(`No se pudo leer ${clean} del sitio publicado.`);return await response.text()}
  async function exportPatchZip(){if(!window.JSZip)throw new Error("No se pudo cargar JSZip.");const files=await listPatches(),names=Object.keys(files);if(!names.length)throw new Error("No hay cambios pendientes.");const zip=new JSZip();names.forEach(path=>zip.file(path,files[path]));zip.file("INSTRUCCIONES.txt",`ACTUALIZACIÓN PARCIAL DEL SITIO\n\nCopia el contenido sobre la raíz del sitio existente.\n\nArchivos incluidos:\n${names.map(n=>"- "+n).join("\n")}\n`);const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`gutierrezvidal-actualizacion-${new Date().toISOString().slice(0,10)}.zip`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
  async function status(){const files=await listPatches();return{count:Object.keys(files).length,paths:Object.keys(files).sort(),updatedAt:await getValue("updatedAt")}}
  window.GVPatches={getFile,savePatch,removePatch,listPatches,exportPatchZip,clearAll,status};
})();
