"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const ROOT=path.resolve(__dirname,"..");
const modules=["limes-core.js","spanish-semantics.js","entity-engine.js","semantic-engine.js","event-engine.js","game-ontology.js","synthesis-engine.js","game-engine.js","analysis-engine.js"];
const sandbox={window:{},console,Number,Math,String,JSON,Map,Set,RegExp,Error,Date,Intl,fetch:async()=>{throw new Error("offline")}};sandbox.window=sandbox;vm.createContext(sandbox);for(const f of modules)vm.runInContext(fs.readFileSync(path.join(ROOT,"js",f),"utf8"),sandbox,{filename:f});
const ns=sandbox.Limes52;ns.Spanish.loadDictionary=async()=>({status:"test-stub",size:0,affixRules:0});
const T=[];const test=(name,fn)=>T.push({name,fn});const analyze=raw=>ns.Analysis.analyze(raw);
const REG=`La Comunidad de Pequeños Anfitriones rechazó el límite impuesto por las autoridades capitalinas. Los anfitriones indicaron que existe ambigüedad en la aplicación de la norma. Por ello exhortaron al Gobierno de la Ciudad de México a establecer mesas de trabajo para revisar el tema y eliminarla. También dijeron que han entregado propuestas al Congreso de la Ciudad de México. “Nosotros no causamos la crisis de vivienda en esta ciudad y quitarnos del camino no resolverá el problema”, agregaron. No hay un estudio, no hay un diagnóstico, dijo Blanca Lolbé, integrante de la comunidad. En 2024, las autoridades capitalinas reformaron la Ley de Turismo local y se estableció un tope máximo del 50 por ciento de las noches al año.`;
const NARR=`La madrastra propuso abandonar a los niños en el bosque. El padre se resistió, pero finalmente accedió. Hänsel recogió guijarros y los fue dejando por el camino. Los niños regresaron a casa. Días después volvieron a abandonarlos; Hänsel intentó marcar el camino con migas, pero los pájaros se las comieron y no pudieron regresar. Una bruja encerró a Hänsel para engordarlo. Gretel empujó a la bruja dentro del horno, cerró la puerta y liberó a Hänsel. Encontraron piedras preciosas y regresaron a casa.`;
const MIG=`En sustitución de la presidenta Claudia Sheinbaum Pardo, la titular de Gobernación Rosa Icela Rodríguez encabezó la conferencia. Indicó que México recibe directamente a sus connacionales mediante un acuerdo con autoridades de Estados Unidos. Agregó que no comparten que los connacionales sean trasladados a un tercer país antes de llegar a México. El Instituto Nacional de Migración participa en la recepción y CBP coordina procedimientos fronterizos.`;
const EARLY=`Junto a un bosque muy grande vivía un pobre leñador con su mujer y dos hijos; el niño se llamaba Hänsel y la niña, Gretel. Estaba el leñador una noche en la cama, cavilando y revolviéndose, sin que las preocupaciones le dejaran pegar el ojo; finalmente, dijo, suspirando, a su mujer: ¿Qué va a ser de nosotros? ¿Cómo alimentar a los pobres pequeños, puesto que nada nos queda? Se me ocurre una cosa -respondió ella-. Mañana, de madrugada, nos llevaremos a los niños a lo más espeso del bosque. ¡Por Dios, mujer! -replicó el hombre-. Eso no lo hago yo.`;

test("core v0.40 permanece exacto",()=>{const r=ns.Core.predictInteraction({id:"A",S:.8,E:.7,H:.1},{id:"B",S:.5,E:.5,H:.2},{source:"A",target:"B",D:.7,phi:.5,G:.8});assert(Math.abs(r.R-.56)<1e-12);assert(Math.abs(r.X-.196)<1e-12);assert(Math.abs(r.deltaH-.1176)<1e-12);});
test("lemmatizer no convierte guijarros en guiar",()=>assert.strictEqual(ns.Spanish.lemma("guijarros"),"guijarros"));
test("para no se convierte en parar",()=>assert.strictEqual(ns.Spanish.lemma("para"),"para"));
test("infinitivo con clítico no se trata como verbo finito",()=>assert.strictEqual(ns.Spanish.isLikelyFiniteVerb("eliminarla"),false));
test("coordinación con infinitivo permanece dentro del acto de petición",()=>{const c=ns.Spanish.splitClauses("Exhortaron al Gobierno a revisar el tema y eliminarla.");assert.strictEqual(c.length,1);});
test("coordinación con nuevo verbo finito se segmenta",()=>{assert.strictEqual(ns.Spanish.splitClauses("Encontraron piedras preciosas y regresaron a casa.").length,2);assert.strictEqual(ns.Spanish.splitClauses("El Instituto participa y CBP coordina procedimientos.").length,2);});

test("NER bloquea falsos nombres del reporte narrativo",async()=>{const a=await analyze("Cómo saldremos. Anduvieron toda la noche. Espera un poco. Vamos, no te entretengas. Míos son. También dijeron algo.");const n=a.entities.map(e=>e.name);for(const x of ["Cómo","Anduvieron","Espera","Vamos","Míos","También"])assert(!n.includes(x),x);});
test("NER bloquea objetos no agentes como colectivos",async()=>{const a=await analyze("Los bolsillos estaban llenos. Los ojos se cerraron. Los temas fueron tratados. Las preocupaciones no lo dejaban dormir.");const n=a.entities.map(e=>e.name);for(const x of ["los bolsillos","los ojos","los temas","las preocupaciones"])assert(!n.includes(x),x);});
test("agentes ambientales no se convierten en actores estratégicos",async()=>{const a=await analyze("Los pájaros se comieron las migas. Las fieras rondaban el bosque.");assert(!a.semiotic.actors.some(x=>/pájaros|fieras/i.test(x.id)));});
test("Dios se conserva como referente no operativo",async()=>{const a=await analyze("Dios Nuestro Señor nos ayudará, dijo el niño.");const e=a.entities.find(x=>/Dios/.test(x.name));assert(e);assert.strictEqual(e.operationalCandidate,false);assert(!a.semiotic.actors.some(x=>/Dios/.test(x.id)));});
test("identidad narrativa niño/niña se enlaza con nombres",async()=>{const a=await analyze("El niño se llamaba Hänsel y la niña, Gretel.");const h=a.entities.find(e=>e.name==="Hänsel"),g=a.entities.find(e=>e.name==="Gretel");assert(h&&h.aliases.includes("niño"));assert(g&&g.aliases.includes("niña"));});
test("Martes Ciudadano es programa y no persona",async()=>{const a=await analyze("También dijeron que asistieron al Martes Ciudadano encabezado por Clara Brugada.");const e=a.entities.find(x=>x.name==="Martes Ciudadano");assert(e);assert.strictEqual(e.type,"PROGRAM");assert.strictEqual(e.operationalCandidate,false);assert(!a.entities.some(x=>x.name==="También"));});
test("Blanca Lolbé conserva diacrítico",async()=>{const a=await analyze("No hay diagnóstico, dijo Blanca Lolbé, integrante de la comunidad.");assert(a.entities.some(x=>x.name==="Blanca Lolbé"));});

test("hablante postpuesto en diálogo se resuelve",async()=>{const a=await analyze(EARLY);const f=a.semantic.frames.find(x=>x.predicate==="replicar");assert(f);assert.strictEqual(f.actor,"hombre");});
test("atribución con destinatario no convierte destinatario en hablante",async()=>{const a=await analyze(EARLY);const f=a.semantic.frames.find(x=>x.predicate==="decir"&&/finalmente/.test(x.evidence));assert(f);assert.strictEqual(f.actor,"leñador");assert.strictEqual(f.recipient,"mujer");});
test("pronombre ella recupera destinataria inmediata",async()=>{const a=await analyze(EARLY);const f=a.semantic.frames.find(x=>x.predicate==="responder");assert(f);assert.strictEqual(f.actor,"mujer");});
test("discurso futuro se representa como Decir con contenido propuesto",async()=>{const a=await analyze(EARLY);const f=a.semantic.frames.find(x=>/nos llevaremos/.test(x.evidence));assert(f);assert.strictEqual(f.type,"DECIR");assert.strictEqual(f.actor,"mujer");assert.strictEqual(f.contentPredicate,"llevar");assert.strictEqual(f.content_realization,"announced/proposed");});
test("negación en primera persona permanece como contenido discursivo",async()=>{const a=await analyze(EARLY);const f=a.semantic.frames.find(x=>/no lo hago yo/.test(x.evidence));assert(f);assert.strictEqual(f.type,"DECIR");assert.strictEqual(f.actor,"hombre");assert.strictEqual(f.contentPredicate,"hacer");});

test("regulación: nested frame distingue imponer de rechazar",async()=>{const a=await analyze(REG);const imp=a.semantic.frames.find(x=>x.nested&&x.predicate==="imponer"),rej=a.semantic.frames.find(x=>x.predicate==="rechazar");assert(imp&&/autoridades/.test(imp.actor));assert(rej&&/Comunidad/.test(rej.actor));});
test("regulación: exhortación hereda anfitriones y Gobierno es receptor",async()=>{const a=await analyze(REG);const f=a.semantic.frames.find(x=>x.predicate==="exhortar");assert(f);assert(/anfitriones/i.test(f.actor));assert(/Gobierno de la Ciudad de México/.test(f.recipient));});
test("regulación: revisar/eliminar son contenido propuesto, no HACER realizado",async()=>{const a=await analyze(REG);const f=a.semantic.frames.find(x=>x.predicate==="exhortar");assert(f.contentPredicates.includes("revisar")&&f.contentPredicates.includes("eliminar"));assert.strictEqual(f.content_realization,"proposed");assert(!a.semantic.frames.some(x=>x.type==="HACER"&&x.predicate==="eliminar"&&/exhortaron/.test(x.evidence)));});
test("regulación: También dijeron conserva hablante anterior",async()=>{const a=await analyze(REG);const f=a.semantic.frames.find(x=>x.predicate==="decir"&&/^También/.test(x.evidence));assert(f);assert(/anfitriones/i.test(f.actor));assert(/Congreso/.test(f.recipient));});
test("regulación: quitarnos del camino no es retorno/orientación",async()=>{const a=await analyze(REG);const f=a.semantic.frames.find(x=>/quitarnos del camino/.test(x.evidence));assert(f);assert.notStrictEqual(f.object,"retorno / orientación");assert.strictEqual(f.object,"actividad / participación");});
test("regulación: síntesis reduce actos a dos programas principales",async()=>{const a=await analyze(REG);assert.strictEqual(a.semiotic.programs.length,2);assert(a.semiotic.programs.some(p=>p.label==="Programa regulatorio"));assert(a.semiotic.programs.some(p=>/Contra-programa/.test(p.label)));assert.strictEqual(a.semiotic.counterPrograms.length,1);});
test("regulación: lugares y ley no son actores ni fronteras",async()=>{const a=await analyze(REG);for(const x of ["Ciudad de México","México","Ley de Turismo"])assert(!a.semiotic.actors.some(y=>y.id===x),x);assert(!a.semiotic.frontiers.some(f=>/Ciudad de México$|México$|Ley de Turismo$/.test(f.target)&&!/^Gobierno|^Congreso/.test(f.target)));});
test("regulación: objeto de valor distingue capacidad de operar de restricción",async()=>{const a=await analyze(REG);assert(a.semiotic.valueObjects.some(o=>o.kind==="objeto de valor"&&/operar|trabajar/.test(o.object)));assert(a.semiotic.valueObjects.some(o=>/obstáculo/.test(o.kind)&&/restricción/.test(o.object)));});

test("narrativa: no crea falsos actores de forma verbal",async()=>{const a=await analyze(NARR);const names=a.semiotic.actors.map(x=>x.id);for(const x of ["Cómo","Anduvieron","Espera","Vamos","Míos","los bolsillos"])assert(!names.includes(x),x);});
test("narrativa: guijarros son acción de Hänsel",async()=>{const a=await analyze(NARR);const f=a.semantic.frames.find(x=>x.predicate==="dejar"&&/camino/.test(x.evidence));assert(f);assert.strictEqual(f.actor,"Hänsel");});
test("narrativa: captura y abandono son programas distintos",async()=>{const a=await analyze(NARR);assert(a.semiotic.programs.some(p=>p.label==="Programa de abandono"));assert(a.semiotic.programs.some(p=>p.label==="Programa de captura"));});
test("narrativa: orientación y liberación son contra-programas distintos",async()=>{const a=await analyze(NARR);assert(a.semiotic.programs.some(p=>/orientación/.test(p.label)));assert(a.semiotic.programs.some(p=>/liberación/.test(p.label)));});
test("narrativa: adquisición de recursos se separa del retorno",async()=>{const a=await analyze(NARR);assert(a.semiotic.programs.some(p=>/Adquisición de recursos/.test(p.label)));assert(a.semiotic.programs.some(p=>/Retorno/.test(p.label)));});
test("narrativa: reconstruye al menos dos subgames",async()=>{const a=await analyze(NARR);assert(a.semiotic.subgames.length>=2);assert(a.semiotic.subgames.some(s=>/madrastra/.test(s.actors.join(" "))));assert(a.semiotic.subgames.some(s=>/bruja/.test(s.actors.join(" "))));});
test("narrativa: varios subgames impiden juego canónico global",async()=>{const a=await analyze(NARR);assert.strictEqual(a.game.globalGate,false);assert.strictEqual(a.game.determined,null);assert(/subgame/.test(a.qualitative.strategic.label));});
test("narrativa: contraacción de Gretel apunta a la bruja",async()=>{const a=await analyze(NARR);const f=a.semantic.frames.find(x=>x.predicate==="empujar");assert(f);assert.strictEqual(f.actor,"Gretel");assert.strictEqual(f.patient,"bruja");});

test("migración: dominio emerge del texto",async()=>{const a=await analyze(MIG);assert.strictEqual(a.events.domain.id,"migracion");});
test("migración: Gobernación y Rosa Icela quedan separadas por tipo",async()=>{const a=await analyze(MIG);const g=a.entities.find(e=>e.name==="Gobernación"),r=a.entities.find(e=>e.name==="Rosa Icela Rodríguez");assert(g&&g.type==="GOVERNMENT");assert(r&&r.type==="PERSON");});
test("migración: Indicó/Agregó heredan a Rosa Icela como hablante",async()=>{const a=await analyze(MIG);for(const p of ["indicar","agregar"]){const f=a.semantic.frames.find(x=>x.predicate===p);assert(f,p);assert.strictEqual(f.actor,"Rosa Icela Rodríguez");}});
test("migración: traslado pasivo citado no convierte a Rosa ni México en agente material",async()=>{const a=await analyze(MIG);assert(!a.semantic.frames.some(f=>f.type==="HACER"&&f.predicate==="trasladar"&&["Rosa Icela Rodríguez","México"].includes(f.actor)));assert(!a.semiotic.programs.some(p=>p.label==="Traslado a tercer país"&&["Rosa Icela Rodríguez","México"].includes(p.actor)));});
test("migración: INM y CBP se segmentan como operaciones distintas",async()=>{const a=await analyze(MIG);const f1=a.semantic.frames.find(f=>f.actor==="Instituto Nacional de Migración"&&f.predicate==="participar"),f2=a.semantic.frames.find(f=>f.actor==="CBP"&&f.predicate==="coordinar");assert(f1&&f2);});
test("migración: issue se deriva del dominio sin copiar el caso",async()=>{const a=await analyze(MIG);assert(/movilidad|recepción|repatriación|traslado/.test(a.scenario.issue));assert(!/transformación conductual respecto de la cuestión/.test(a.scenario.issue));});

test("fronteras sólo conectan actores operativos",async()=>{for(const raw of [REG,NARR,MIG]){const a=await analyze(raw),allowed=new Set(a.semiotic.actors.map(x=>x.id));for(const f of a.semiotic.frontiers){assert(allowed.has(f.source),f.source);assert(allowed.has(f.target),f.target);}}});
test("ningún juego rellena D phi G",async()=>{const a=await analyze(REG);for(const o of a.events.operations){assert.strictEqual(o.D,null);assert.strictEqual(o.phi,null);assert.strictEqual(o.G,null);}});
test("catálogo conserva 76 juegos",()=>assert.strictEqual(ns.GameOntology.count,76));
test("producción no reintroduce expected utility ni normalización tetrádica",()=>{const prod=modules.concat(["app.js"]).map(f=>fs.readFileSync(path.join(ROOT,"js",f),"utf8")).join("\n").toLowerCase();assert(!prod.includes("expectedutility"));assert(!prod.includes("function utility"));assert(!prod.includes("normalizestates"));});
test("interfaz no enumera parámetros vacíos cuando no hay cálculo",()=>{const app=fs.readFileSync(path.join(ROOT,"js/app.js"),"utf8");assert(app.includes("No se enumeran parámetros vacíos"));assert(app.includes("No hay componentes numéricos sustentados"));});
test("sin JavaScript monolítico inline y formulario fuente vacío",()=>{const html=fs.readFileSync(path.join(ROOT,"index.html"),"utf8");assert(!/<script(?![^>]*src=)[^>]*>[\s\S]*?<\/script>/i.test(html));assert(/<textarea id="corpus"[^>]*><\/textarea>/.test(html));});

(async()=>{let pass=0;for(const t of T){try{await t.fn();console.log("PASS",t.name);pass++;}catch(e){console.error("FAIL",t.name,"\n ",e.stack||e.message);}}console.log(`\n${pass}/${T.length} PASS`);if(pass!==T.length)process.exit(1);})();
