"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const ROOT=path.resolve(__dirname,"..");
const files=["limes-core.js","spanish-semantics.js","entity-engine.js","semantic-engine.js","event-engine.js","game-ontology.js","synthesis-engine.js","game-engine.js","analysis-engine.js"];
const sandbox={window:{},console,Number,Math,String,JSON,Map,Set,RegExp,Error,Date,Intl,fetch:async()=>{throw new Error("offline test");}};sandbox.window=sandbox;vm.createContext(sandbox);for(const f of files)vm.runInContext(fs.readFileSync(path.join(ROOT,"js",f),"utf8"),sandbox,{filename:f});
const ns=sandbox.Limes52;ns.Spanish.loadDictionary=async()=>({status:"test-stub",size:0,affixRules:0});
const tests=[];function test(name,fn){tests.push({name,fn});}
function analyze(raw){return ns.Analysis.analyze(raw);}

test("core conserva ecuación v0.40",()=>{const r=ns.Core.predictInteraction({id:"A",S:.8,E:.7,H:.1},{id:"B",S:.5,E:.5,H:.2},{source:"A",target:"B",D:.7,phi:.5,G:.8});assert(Math.abs(r.R-.56)<1e-12);assert(Math.abs(r.X-.196)<1e-12);assert(Math.abs(r.deltaH-.1176)<1e-12);});
test("core restaura contrato source/target",()=>{assert.throws(()=>ns.Core.predictInteraction({id:"A",S:.8,E:.7,H:.1},{id:"B",S:.5,E:.5,H:.2},{source:"X",target:"B",D:.7,phi:.5,G:.8}),/Source\/target/);});
test("sin nombres de fixtures en producción",()=>{const prod=files.concat(["app.js"]).map(f=>fs.readFileSync(path.join(ROOT,"js",f),"utf8")).join("\n");for(const x of ["Fausto Corrales","Corrales Rodríguez","Sheinbaum","Zambada","Pequeños Anfitriones","Hänsel y Gretel"])assert(!prod.includes(x),x);});
test("detenerse a escuchar no es detención jurídica",async()=>{const a=await analyze("Los niños se detuvieron a escuchar un pájaro. Después siguieron caminando por el bosque.");assert.notStrictEqual(a.events.domain.id,"investigacion");assert(!a.semantic.frames.some(f=>f.sense==="LEGAL_DETENTION"));});
test("detención jurídica transitive conserva actor del texto",async()=>{const a=await analyze("La Policía Municipal detuvo a Juan Pérez por orden judicial. El juez confirmó la medida.");const names=a.entities.map(e=>e.name);assert(names.some(x=>/Juan Pérez/.test(x)));assert(!names.some(x=>/Corrales|Fiscalía General de la República/.test(x)));const f=a.semantic.frames.find(x=>x.sense==="LEGAL_DETENTION");assert(f);assert(/Juan Pérez/.test(f.patient)||a.events.operations.some(o=>/Juan Pérez/.test(o.actionTarget)));});
test("NER no crea Corrió/Dijo/Pero/Volcó como PERSON",async()=>{const a=await analyze("Corrió Gretel hacia la casa. Dijo Hänsel que volvería. Pero Gretel siguió. Volcó Gretel su delantal.");const names=a.entities.map(e=>e.name);for(const bad of ["Corrió Gretel","Dijo Hänsel","Pero Gretel","Volcó Gretel"])assert(!names.includes(bad),bad);});
test("frames anidados separan imponer y rechazar",async()=>{const a=await analyze("La Asociación de Comerciantes rechazó el límite impuesto por el Ayuntamiento de Puebla.");const imp=a.semantic.frames.find(f=>f.sense==="INSTITUTIONAL_IMPOSITION"&&f.nested);assert(imp,"nested imposition");assert(/Ayuntamiento/.test(imp.actor));const rej=a.semantic.frames.find(f=>f.predicate==="rechazar");assert(rej,"rejection frame");assert(/Asociación/.test(rej.actor));});
test("UNRESOLVED sustituye HACER residual",async()=>{const a=await analyze("El cielo, intensamente azul.");assert(a.semantic.frames.some(f=>f.type==="UNRESOLVED")||a.semantic.frames.length===0);assert(!a.semantic.frames.some(f=>f.type==="HACER"&&!f.predicate));});
test("regulación genérica se reconoce sin fixture",async()=>{const a=await analyze("El Ayuntamiento de Puebla estableció una restricción de horarios para los taxistas. El Sindicato de Taxistas rechazó la medida y pidió revisarla.");assert.strictEqual(a.events.domain.id,"regulacion");});
test("continuidad discursiva no convierte Gobierno en hablante",async()=>{const a=await analyze("La Asociación de Comerciantes rechazó la medida. Indicaron que se han acercado al Gobierno de Puebla varias veces.");const f=a.semantic.frames.find(x=>x.predicate==="indicar");assert(f);assert(/Asociación de Comerciantes/.test(f.actor),f.actor);});
test("acciones materiales quedan fuera del núcleo v0.40",async()=>{const a=await analyze("La Policía Municipal detuvo a Juan Pérez por orden judicial.");const det=a.events.operations.find(o=>o.family==="judicial_detention");assert(det);assert.strictEqual(det.coreEligible,false);assert(/theoretical extension pending/.test(det.eligibility));});
test("ninguna operación recibe D phi G automáticos",async()=>{const a=await analyze("El Ayuntamiento de Puebla impuso un límite. La Asociación de Comerciantes pidió al Ayuntamiento retirar la medida.");for(const o of a.events.operations){assert.strictEqual(o.D,null);assert.strictEqual(o.phi,null);assert.strictEqual(o.G,null);assert.strictEqual(o.calculable,false);}});
test("actores de track no reciben S/E/H automáticos",async()=>{const a=await analyze("El Ayuntamiento de Puebla impuso un límite. La Asociación de Comerciantes pidió al Ayuntamiento retirar la medida.");const actors=ns.Analysis.actorsForTrack(a,a.tracks[0]);for(const x of actors){assert.strictEqual(x.S,null);assert.strictEqual(x.E,null);assert.strictEqual(x.H,null);}});
test("juego exige todos los requisitos",()=>{const g=ns.GameOntology.byId.get("screening"),features=new Set(["screening","information_asymmetry","principal_queries","informed_actor"]),r=ns.Games.scoreGame(g,features);assert.strictEqual(r.eligible,false);assert(r.missing.includes("uninformed_actor"));});
test("mera detención no determina Screening",async()=>{const a=await analyze("La Policía Municipal detuvo a Juan Pérez por orden judicial.");assert(!a.game.determined||a.game.determined.gameId!=="screening");});
test("escenarios no inventan Gτ numérico",async()=>{const a=await analyze("El Ayuntamiento de Puebla impuso un límite. La Asociación de Comerciantes pidió revisar la medida.");for(const s of a.game.scenarios)assert.deepStrictEqual(JSON.parse(JSON.stringify(s.terminalG)),{});});
test("diccionario participa en NER",()=>{const src=fs.readFileSync(path.join(ROOT,"js/entity-engine.js"),"utf8");assert(src.includes("inDictionary"));});
test("Gτ vacío no se convierte a cero",()=>{const src=fs.readFileSync(path.join(ROOT,"js/app.js"),"utf8");assert(src.includes('rawTg===""?null:Number(rawTg)'));});
test("sin numericFor ni presets numéricos de actor",()=>{const ev=fs.readFileSync(path.join(ROOT,"js/event-engine.js"),"utf8"),an=fs.readFileSync(path.join(ROOT,"js/analysis-engine.js"),"utf8");assert(!ev.includes("function numericFor"));assert(!/S=\.[0-9]|E=\.[0-9]|H0:\s*\.[0-9]/.test(an));});

test("operaciones sólo usan entidades presentes o actor analítico explícito",async()=>{const raw="La Policía Municipal detuvo a Juan Pérez por orden judicial. El Ayuntamiento de Puebla anunció una revisión.";const a=await analyze(raw);const names=new Set(a.entities.map(e=>e.name));for(const o of a.events.operations){for(const id of [o.source,o.actionTarget])if(id)assert(names.has(id),`entidad no textual: ${id}`);}});
test("una mención temática aislada no fuerza dominio judicial",async()=>{const a=await analyze("La palabra detención apareció en el informe como título de una sección, sin describir actuación alguna.");assert.notStrictEqual(a.events.domain.id,"investigacion");});
test("coreferencia no crea episodios gigantes por etiqueta genérica",async()=>{const raw="Ana dijo que volvería. Pedro abrió la puerta. Ana caminó al patio. Pedro cerró la ventana. Ana respondió que estaba cansada. Pedro salió de la casa.";const a=await analyze(raw);assert(Math.max(0,...a.events.episodes.map(e=>e.evidenceCount))<=4);});
test("featureSet no inyecta features por dominio",()=>{const src=fs.readFileSync(path.join(ROOT,"js/game-engine.js"),"utf8");assert(!src.includes("domainBoost"));assert(!/if\(domain===/.test(src));});
test("todos los tracks automáticos quedan preliminares",async()=>{const a=await analyze("El Ayuntamiento de Puebla estableció una restricción. La Asociación de Comerciantes pidió revisarla.");assert(a.tracks.every(t=>t.status.calculable===false));});
test("filas manuales parten sin valores numéricos",()=>{const src=fs.readFileSync(path.join(ROOT,"js/app.js"),"utf8");assert(src.includes('S:null,E:null,H:null'));assert(src.includes('D:null,phi:null,G:null'));});
test("formulario de despliegue no contiene presets analíticos",()=>{const index=fs.readFileSync(path.join(ROOT,"index.html"),"utf8");assert(/<textarea id="corpus"[^>]*><\/textarea>/.test(index));assert(index.includes('id="issue" value=""'));assert(/<textarea id="scenarioNote"[^>]*><\/textarea>/.test(index));});
test("catálogo de juegos se conserva completo",()=>{assert.strictEqual(ns.GameOntology.count,76);});
test("síntesis semiótica existe antes de la mediación estratégica",async()=>{const a=await analyze("El Ayuntamiento de Puebla impuso una restricción a los comercios. La Asociación de Comerciantes rechazó la restricción y pidió al Ayuntamiento revisarla.");assert(a.semiotic);assert(a.qualitative);assert(a.semiotic.programs.length>=2);assert(a.semiotic.counterPrograms.length>=1);assert(a.qualitative.strategic);});
test("síntesis recupera oposiciones sin normalizar estados",async()=>{const a=await analyze("El Ayuntamiento mantuvo una restricción. La Asociación pidió modificar y eliminar la restricción.");assert(a.semiotic.oppositions.some(o=>/restricción|mantenimiento/.test(o.left+o.right)));const prod=files.map(f=>fs.readFileSync(path.join(ROOT,"js",f),"utf8")).join("\n");assert(!prod.includes("normalizeStates"));});
test("análisis cualitativo sobrevive sin valores numéricos",async()=>{const a=await analyze("La Asociación informó al Ayuntamiento que rechazaba la medida y solicitó revisarla.");assert(a.qualitative.analysisSummary!==undefined);assert(a.qualitative.quantification.variables.every(v=>v.numeric===false));});
test("teoría de juegos media pero no asigna variables Limes",async()=>{const a=await analyze("El Ayuntamiento impuso una restricción. La Asociación rechazó la medida y pidió negociar su modificación.");assert(a.game);for(const o of a.events.operations){assert.strictEqual(o.D,null);assert.strictEqual(o.phi,null);assert.strictEqual(o.G,null);}});
test("extrapolación cualitativa requiere estructura interpretable",async()=>{const a=await analyze("El Ayuntamiento impuso una restricción. La Asociación rechazó la medida y pidió negociar su modificación.");assert(a.qualitative.strategic.scenarios.length>=1);const b=await analyze("El cielo estaba gris sobre la plaza.");assert.strictEqual(b.qualitative.strategic.scenarios.length,0);});
test("core calcula componentes parciales sin inventar faltantes",()=>{const r=ns.Core.partialInteraction({id:"A",S:.8,E:.5,H:NaN},{id:"B",S:NaN,E:NaN,H:NaN},{source:"A",target:"B",D:NaN,phi:NaN,G:NaN});assert.strictEqual(r.R,.4);assert.strictEqual(r.deltaH,null);assert(r.missing.includes("D")&&r.missing.includes("G"));});
test("interfaz prioriza semiótica y oculta trazabilidad en details",()=>{const index=fs.readFileSync(path.join(ROOT,"index.html"),"utf8"),app=fs.readFileSync(path.join(ROOT,"js/app.js"),"utf8");assert(index.includes("Semiótica → mediación estratégica"));assert(index.includes('<details id="tracePanel"'));assert(app.includes("Análisis cualitativo"));assert(app.includes("Mediación estratégica y extrapolación"));});
test("interfaz no bloquea análisis con mensaje Falta S",()=>{const app=fs.readFileSync(path.join(ROOT,"js/app.js"),"utf8"),index=fs.readFileSync(path.join(ROOT,"index.html"),"utf8");assert(!app.includes("Falta S para"));assert(!index.includes("Falta S"));});
test("no se reintroduce expected utility de la monolítica",()=>{const prod=files.concat(["app.js"]).map(f=>fs.readFileSync(path.join(ROOT,"js",f),"utf8")).join("\n").toLowerCase();assert(!prod.includes("expectedutility"));assert(!prod.includes("function utility"));assert(!prod.includes("probabilidad de victoria"));});

test("nota judicial completa queda en mediación informativa sin Screening canónico",async()=>{const raw=fs.readFileSync(path.join(ROOT,"tests/fixtures/judicial-news.txt"),"utf8"),a=await analyze(raw);assert.strictEqual(a.events.domain.id,"investigacion");assert.strictEqual(a.qualitative.strategic.label,"interacción estratégica de información");assert(!a.game.determined||a.game.determined.gameId!=="screening");});
test("de acuerdo con no cuenta como acuerdo estratégico",async()=>{const a=await analyze("De acuerdo con el informe, la autoridad investiga los hechos.");assert(!a.game.features.includes("agreement"));});
test("narrativa breve atribuye contraacción a Gretel",async()=>{const a=await analyze("La bruja encerró a Hänsel. Gretel empujó a la bruja, abrió la reja y escaparon. Los niños regresaron a casa.");const c=a.events.episodes.find(e=>e.family==="counteraction");assert(c);assert.strictEqual(c.frames[0].actor,"Gretel");});
test("Alternating Offers exige señal explícita de alternancia",()=>{const g=ns.GameOntology.byId.get("alternating_offers"),r=ns.Games.scoreGame(g,new Set(["bargaining","sequential","offers","negotiable_outcome"]));assert.strictEqual(r.eligible,false);assert(r.missing.length===0);});
test("material/institucional no se transforma silenciosamente en D",async()=>{const a=await analyze("El Ayuntamiento de Puebla impuso un límite a los comercios.");const op=a.events.operations.find(o=>o.family==="regulatory_restriction");assert(op);assert.strictEqual(op.coreEligible,false);assert.strictEqual(op.D,null);});

(async()=>{let pass=0;for(const t of tests){try{await t.fn();console.log("PASS",t.name);pass++;}catch(e){console.error("FAIL",t.name,"\n ",e.stack||e.message);}}console.log(`\n${pass}/${tests.length} PASS`);if(pass!==tests.length)process.exit(1);})();
