"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm"),assert=require("assert");
const root=path.resolve(__dirname,"..");
const sandbox={window:{},console,Number,Math,String,JSON,Map,Set,RegExp,Error,Date,Promise};sandbox.window=sandbox;
sandbox.fetch=async function(url){const p=path.join(root,String(url));return{ok:fs.existsSync(p),status:fs.existsSync(p)?200:404,text:async()=>fs.readFileSync(p,"utf8")};};
vm.createContext(sandbox);
for(const file of ["limes-core.js","spanish-semantics.js","entity-engine.js","semantic-engine.js","event-engine.js","game-ontology.js","game-engine.js","analysis-engine.js"]){vm.runInContext(fs.readFileSync(path.join(root,"js",file),"utf8"),sandbox,{filename:file});}
const L=sandbox.Limes52;
const tests=[];const test=(n,f)=>tests.push([n,f]);
const judicial=`La presidenta Claudia Sheinbaum calificó como “relevante” la detención de Fausto Corrales Rodríguez, señalado por la Fiscalía General de la República (FGR) como probable responsable de encubrimiento y falsedad de declaraciones. La captura podría aportar información para esclarecer lo ocurrido. Sheinbaum pidió esperar la información oficial. Las investigaciones de la Fiscalía General de la República permanecen abiertas. La Fiscalía Especial de Investigación y Litigación de Casos Complejos, adscrita a la Fiscalía Especializada de Control Regional (FECOR), realizó la detención en coordinación con elementos de la Policía Federal Ministerial (PFM) y de Interpol, pertenecientes a la Agencia de Investigación Criminal (AIC). La aprehensión se realizó en cumplimiento de una orden emitida por un juez de Control federal. La FGR atribuye a Corrales una probable participación en encubrimiento. Según la Fiscalía, habría presentado contradicciones y omitido información. La hipótesis de la autoridad es que esas inconsistencias pudieron obstaculizar su esclarecimiento.`;
const regulation=`La Comunidad de Pequeños Anfitriones rechazó el límite impuesto por las autoridades capitalinas de sólo poder ofrecer hospedaje eventual durante el 50 por ciento de las noches del año. En 2024 las autoridades reformaron la Ley de Turismo y establecieron un tope máximo del 50 por ciento. Los anfitriones pidieron que se elimine la restricción y anunciaron amparos. Los anfitriones han generado recursos para las arcas del Gobierno por concepto del impuesto sobre hospedaje que pagan desde 2017.`;
const narrative=`La madrastra dijo: mañana llevaremos a Hänsel y Gretel al bosque y los dejaremos solos. Al padre le dolía mucho abandonar a los niños. Más tarde los dejaron solos en el bosque. Hänsel fue dejando migas de pan por el camino, pero los pájaros se comieron las migas y no encontraron la ruta. La bruja encerró a Hänsel detrás de una reja. Gretel empujó a la bruja, abrió la puerta y escaparon. Encontraron perlas y piedras preciosas. Después regresaron a casa de su padre y vivieron felices.`;

test("núcleo matemático intacto",()=>{const A={id:"A",S:.8,E:.7,H:.25},B={id:"B",S:.5,E:.6,H:.2},r=L.Core.predictInteraction(A,B,{source:"A",target:"B",D:.7,phi:.5,G:.8});assert(Math.abs(r.R-.56)<1e-12);assert(Math.abs(r.X-.196)<1e-12);assert(Math.abs(r.deltaH-.1176)<1e-12);});
test("diccionario mexicano completo cargable",async()=>{const info=await L.Spanish.loadDictionary();assert.equal(info.status,"loaded");assert(info.size>50000);assert(info.affixRules>1000);});
test("catálogo amplio de juegos",()=>{assert(L.GameOntology.count>=70);assert(L.GameOntology.byId.has("prisoners_dilemma"));assert(L.GameOntology.byId.has("screening"));assert(L.GameOntology.byId.has("signaling"));assert(L.GameOntology.byId.has("nash_bargaining"));assert(L.GameOntology.byId.has("inspection"));assert(L.GameOntology.byId.has("cournot"));assert(L.GameOntology.byId.has("weighted_voting"));});
test("noticia judicial no se clasifica como regulación",async()=>{const a=await L.Analysis.analyze(judicial);assert.equal(a.events.domain.id,"investigacion");assert.notEqual(a.events.domain.id,"regulacion");});
test("noticia judicial recupera actores institucionales y personales",async()=>{const a=await L.Analysis.analyze(judicial),names=a.entities.map(e=>e.name);for(const q of ["Claudia Sheinbaum","Fiscalía General de la República","Fausto Corrales Rodríguez","Fiscalía Especializada de Control Regional","Policía Federal Ministerial","Interpol","Agencia de Investigación Criminal","juez de Control federal"])assert(names.some(x=>x===q),q);assert(names.length>=8);});
test("detención, evaluación, proyección y alegación se distinguen",async()=>{const a=await L.Analysis.analyze(judicial),fs=a.semantic.frames;assert(fs.some(f=>f.sense==="LEGAL_DETENTION"&&f.realization==="realized/asserted"));assert(fs.some(f=>f.sense==="EVALUATION"&&f.type==="DECIR"));assert(fs.some(f=>f.relation_to_event==="projection"&&f.realization==="hypothetical/projected"));assert(fs.some(f=>f.sense==="ATTRIBUTED_ALLEGATION"&&f.epistemic_status==="attributed/alleged"));});
test("proyección judicial no se vuelve operación causal",async()=>{const a=await L.Analysis.analyze(judicial);assert(!a.events.operations.filter(o=>o.family==="projection").some(o=>o.calculable));assert(a.events.operations.some(o=>o.family==="judicial_detention"&&o.calculable));});
test("juego judicial prioriza screening/inspección/información",async()=>{const a=await L.Analysis.analyze(judicial),top=a.game.candidates.slice(0,5).map(x=>x.gameId);assert(top.some(x=>["screening","inspection","bayesian","principal_agent","signaling"].includes(x)),top.join(','));});
test("escenario judicial tiene al menos dos actores operativos",async()=>{const a=await L.Analysis.analyze(judicial),t=a.tracks.find(x=>x.status.calculable)||a.tracks[0],actors=L.Analysis.actorsForTrack(a,t);assert(actors.length>=2);assert(actors.some(x=>/Fiscalía/.test(x.id)&&x.hmode==="sí"));});
test("regulación corefiere restricción y separa argumento fiscal",async()=>{const a=await L.Analysis.analyze(regulation);assert.equal(a.events.domain.id,"regulacion");assert.equal(a.events.episodes.filter(e=>e.family==="regulatory_restriction").length,1);assert(a.events.episodes.some(e=>e.family==="economic_argument"));const op=a.tracks.find(t=>t.id==="impacto_regulatorio");assert.equal(op.operations.length,1);});
test("regulación separa destinatario de H afectado",async()=>{const a=await L.Analysis.analyze(regulation),o=a.events.operations.find(x=>x.family==="regulatory_challenge");assert(o);assert.equal(o.source,"Comunidad de Pequeños Anfitriones");assert.equal(o.actionTarget,"gobierno / autoridades");assert.equal(o.stateTarget,"Comunidad de Pequeños Anfitriones");});
test("plan de abandono y dolor retrospectivo no son abandono causal",async()=>{const a=await L.Analysis.analyze(narrative);const plan=a.semantic.frames.find(f=>/mañana llevaremos/.test(f.evidence));assert(plan&&plan.realization==="announced/proposed");const pain=a.semantic.frames.find(f=>/dolía mucho abandonar/.test(f.evidence));assert(pain&&pain.realization==="remembered/retrospective");const actual=a.events.operations.filter(o=>o.family==="abandonment"&&o.calculable);assert(actual.length>=1);});
test("migas intento+fracaso forman episodio fallido",async()=>{const a=await L.Analysis.analyze(narrative),e=a.events.episodes.find(e=>e.family==="orientation_failure");assert(e);assert(e.evidence.some(x=>/migas/.test(x)));const o=a.events.operations.find(o=>o.family==="orientation_failure");assert(o&&o.G<=.30);});
test("captura, contraacción, recursos y retorno permanecen distintos",async()=>{const a=await L.Analysis.analyze(narrative),families=a.events.episodes.map(e=>e.family);for(const x of ["capture","counteraction","resource_acquisition","return_restoration"])assert(families.includes(x),x);});
test("formularios HTML no contienen presets de contenido",()=>{const h=fs.readFileSync(path.join(root,"index.html"),"utf8");assert(/<textarea id="corpus"[^>]*><\/textarea>/.test(h));assert(/<input id="issue" value=""/.test(h));assert(/<textarea id="scenarioNote"[^>]*><\/textarea>/.test(h));assert(/<tbody><\/tbody>/.test(h));assert(!h.includes("joyería de autor"));});
test("HTML sin JavaScript inline monolítico",()=>{const h=fs.readFileSync(path.join(root,"index.html"),"utf8");assert(!/<script>/.test(h));for(const f of ["limes-core.js","spanish-semantics.js","entity-engine.js","semantic-engine.js","event-engine.js","game-ontology.js","game-engine.js","analysis-engine.js","app.js"])assert(h.includes(`js/${f}`),f);});

test("fixture judicial completo: actores, dominio, screening y operación causal",async()=>{const raw=fs.readFileSync(path.join(root,"tests/fixtures/judicial-news.txt"),"utf8"),a=await L.Analysis.analyze(raw),names=a.entities.map(e=>e.name);assert.equal(a.events.domain.id,"investigacion");for(const q of ["Claudia Sheinbaum","Fiscalía General de la República","Fausto Corrales Rodríguez","Fiscalía Especializada de Control Regional","Policía Federal Ministerial","Interpol","Agencia de Investigación Criminal","juez de Control federal"])assert(names.includes(q),q);assert.equal(a.game.candidates[0].gameId,"screening");const t=a.tracks.find(x=>x.id==="investigacion");assert(t&&t.status.calculable);assert.equal(t.operations.filter(o=>o.calculable).length,1);assert.equal(t.operations[0].family,"judicial_detention");});
test("sin utilidad esperada",()=>{let all="";for(const f of fs.readdirSync(path.join(root,"js")))all+=fs.readFileSync(path.join(root,"js",f),"utf8");assert(!/expectedutility/i.test(all));assert(!/utility\(/i.test(all));});
(async()=>{let pass=0;for(const [n,f] of tests){try{await f();console.log("PASS",n);pass++;}catch(e){console.error("FAIL",n,"\n ",e.message);}}console.log(`\n${pass}/${tests.length} PASS`);if(pass!==tests.length)process.exit(1);})();
